// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type AddUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	ApplicationUser *components.ApplicationUser
	// Error Response
	APIResponseError *components.APIResponseError
}

func (a AddUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddUserResponse) GetApplicationUser() *components.ApplicationUser {
	if a == nil {
		return nil
	}
	return a.ApplicationUser
}

func (a *AddUserResponse) GetAPIResponseError() *components.APIResponseError {
	if a == nil {
		return nil
	}
	return a.APIResponseError
}
