// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type ApproveBeneficiaryRequest struct {
	BeneficiaryID string `pathParam:"style=simple,explode=false,name=beneficiaryId"`
	UserID        string `pathParam:"style=simple,explode=false,name=userId"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string                                     `header:"style=simple,explode=false,name=sub-application"`
	Body           components.UserBeneficiaryValidationRequest `request:"mediaType=application/json"`
}

func (a *ApproveBeneficiaryRequest) GetBeneficiaryID() string {
	if a == nil {
		return ""
	}
	return a.BeneficiaryID
}

func (a *ApproveBeneficiaryRequest) GetUserID() string {
	if a == nil {
		return ""
	}
	return a.UserID
}

func (a *ApproveBeneficiaryRequest) GetSubApplication() *string {
	if a == nil {
		return nil
	}
	return a.SubApplication
}

func (a *ApproveBeneficiaryRequest) GetBody() components.UserBeneficiaryValidationRequest {
	if a == nil {
		return components.UserBeneficiaryValidationRequest{}
	}
	return a.Body
}

type ApproveBeneficiaryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK.
	UserBeneficiaryResponse *components.UserBeneficiaryResponse
}

func (a ApproveBeneficiaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApproveBeneficiaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ApproveBeneficiaryResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ApproveBeneficiaryResponse) GetUserBeneficiaryResponse() *components.UserBeneficiaryResponse {
	if a == nil {
		return nil
	}
	return a.UserBeneficiaryResponse
}
