// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

// CreateUserBeneficiaryRequestBody - User Beneficiary details.
type CreateUserBeneficiaryRequestBody struct {
	// name of the beneficiary
	Name string `json:"name"`
	// Account's details.
	AccountIdentifier components.AccountIdentifier `json:"accountIdentifier"`
}

func (c *CreateUserBeneficiaryRequestBody) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateUserBeneficiaryRequestBody) GetAccountIdentifier() components.AccountIdentifier {
	if c == nil {
		return components.AccountIdentifier{}
	}
	return c.AccountIdentifier
}

type CreateUserBeneficiaryRequest struct {
	UserID string `pathParam:"style=simple,explode=false,name=userId"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
	// The beneficiary to be created.
	Body CreateUserBeneficiaryRequestBody `request:"mediaType=application/json"`
}

func (c *CreateUserBeneficiaryRequest) GetUserID() string {
	if c == nil {
		return ""
	}
	return c.UserID
}

func (c *CreateUserBeneficiaryRequest) GetSubApplication() *string {
	if c == nil {
		return nil
	}
	return c.SubApplication
}

func (c *CreateUserBeneficiaryRequest) GetBody() CreateUserBeneficiaryRequestBody {
	if c == nil {
		return CreateUserBeneficiaryRequestBody{}
	}
	return c.Body
}

type CreateUserBeneficiaryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	UserBeneficiaryResponse *components.UserBeneficiaryResponse
}

func (c CreateUserBeneficiaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserBeneficiaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserBeneficiaryResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateUserBeneficiaryResponse) GetUserBeneficiaryResponse() *components.UserBeneficiaryResponse {
	if c == nil {
		return nil
	}
	return c.UserBeneficiaryResponse
}
