// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type CreateEmbeddedBulkPaymentAuthorisationRequest struct {
	// __Conditional__. Represents the user's login ID for the `Institution` to a personal account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuID *string `header:"style=simple,explode=false,name=psu-id"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a business account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuCorporateID *string `header:"style=simple,explode=false,name=psu-corporate-id"`
	// __Conditional__. The IP address of the PSU.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuIPAddress *string                                            `header:"style=simple,explode=false,name=psu-ip-address"`
	Body         components.BulkPaymentEmbeddedAuthorisationRequest `request:"mediaType=application/json"`
}

func (c *CreateEmbeddedBulkPaymentAuthorisationRequest) GetPsuID() *string {
	if c == nil {
		return nil
	}
	return c.PsuID
}

func (c *CreateEmbeddedBulkPaymentAuthorisationRequest) GetPsuCorporateID() *string {
	if c == nil {
		return nil
	}
	return c.PsuCorporateID
}

func (c *CreateEmbeddedBulkPaymentAuthorisationRequest) GetPsuIPAddress() *string {
	if c == nil {
		return nil
	}
	return c.PsuIPAddress
}

func (c *CreateEmbeddedBulkPaymentAuthorisationRequest) GetBody() components.BulkPaymentEmbeddedAuthorisationRequest {
	if c == nil {
		return components.BulkPaymentEmbeddedAuthorisationRequest{}
	}
	return c.Body
}

type CreateEmbeddedBulkPaymentAuthorisationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfPaymentEmbeddedAuthorisationRequestResponse *components.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse
	// Error Response
	APIResponseError *components.APIResponseError
}

func (c CreateEmbeddedBulkPaymentAuthorisationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEmbeddedBulkPaymentAuthorisationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEmbeddedBulkPaymentAuthorisationResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEmbeddedBulkPaymentAuthorisationResponse) GetAPIResponseOfPaymentEmbeddedAuthorisationRequestResponse() *components.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse {
	if c == nil {
		return nil
	}
	return c.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse
}

func (c *CreateEmbeddedBulkPaymentAuthorisationResponse) GetAPIResponseError() *components.APIResponseError {
	if c == nil {
		return nil
	}
	return c.APIResponseError
}
