// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type CreateHostedPaymentRequestRequest struct {
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string                               `header:"style=simple,explode=false,name=sub-application"`
	Body           components.CreateHostedPaymentRequest `request:"mediaType=application/json"`
}

func (c *CreateHostedPaymentRequestRequest) GetSubApplication() *string {
	if c == nil {
		return nil
	}
	return c.SubApplication
}

func (c *CreateHostedPaymentRequestRequest) GetBody() components.CreateHostedPaymentRequest {
	if c == nil {
		return components.CreateHostedPaymentRequest{}
	}
	return c.Body
}

type CreateHostedPaymentRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfCreateHostedPaymentRequest *components.APIResponseOfCreateHostedPaymentRequest
	// Bad Request
	APIErrorResponseV2 *components.APIErrorResponseV2
}

func (c CreateHostedPaymentRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateHostedPaymentRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateHostedPaymentRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateHostedPaymentRequestResponse) GetAPIResponseOfCreateHostedPaymentRequest() *components.APIResponseOfCreateHostedPaymentRequest {
	if c == nil {
		return nil
	}
	return c.APIResponseOfCreateHostedPaymentRequest
}

func (c *CreateHostedPaymentRequestResponse) GetAPIErrorResponseV2() *components.APIErrorResponseV2 {
	if c == nil {
		return nil
	}
	return c.APIErrorResponseV2
}
