// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type CreateSweepingAuthorisationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfVrpSweepingAuthorisationResponse *components.APIResponseOfVrpSweepingAuthorisationResponse
	// Error Response
	APIErrorResponse *components.APIErrorResponse
}

func (c CreateSweepingAuthorisationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSweepingAuthorisationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSweepingAuthorisationResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSweepingAuthorisationResponse) GetAPIResponseOfVrpSweepingAuthorisationResponse() *components.APIResponseOfVrpSweepingAuthorisationResponse {
	if c == nil {
		return nil
	}
	return c.APIResponseOfVrpSweepingAuthorisationResponse
}

func (c *CreateSweepingAuthorisationResponse) GetAPIErrorResponse() *components.APIErrorResponse {
	if c == nil {
		return nil
	}
	return c.APIErrorResponse
}
