// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type CreateHostedPaymentRequestLinkResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfCreateHostedPaymentRequestLink *components.APIResponseOfCreateHostedPaymentRequestLink
	// Bad Request
	APIErrorResponseV2 *components.APIErrorResponseV2
}

func (c CreateHostedPaymentRequestLinkResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateHostedPaymentRequestLinkResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateHostedPaymentRequestLinkResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateHostedPaymentRequestLinkResponse) GetAPIResponseOfCreateHostedPaymentRequestLink() *components.APIResponseOfCreateHostedPaymentRequestLink {
	if c == nil {
		return nil
	}
	return c.APIResponseOfCreateHostedPaymentRequestLink
}

func (c *CreateHostedPaymentRequestLinkResponse) GetAPIErrorResponseV2() *components.APIErrorResponseV2 {
	if c == nil {
		return nil
	}
	return c.APIErrorResponseV2
}
