// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type CreatePaymentPreAuthorisationRequestRequest struct {
	// __Optional__. Used to obtain the raw request and response to and from the `Institution`.
	Raw *bool `queryParam:"style=form,explode=true,name=raw"`
	// __Conditional__. The IP address of the PSU.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuIPAddress *string `header:"style=simple,explode=false,name=psu-ip-address"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string                                   `header:"style=simple,explode=false,name=sub-application"`
	Body           components.PaymentPreAuthorisationRequest `request:"mediaType=application/json"`
}

func (c *CreatePaymentPreAuthorisationRequestRequest) GetRaw() *bool {
	if c == nil {
		return nil
	}
	return c.Raw
}

func (c *CreatePaymentPreAuthorisationRequestRequest) GetPsuIPAddress() *string {
	if c == nil {
		return nil
	}
	return c.PsuIPAddress
}

func (c *CreatePaymentPreAuthorisationRequestRequest) GetSubApplication() *string {
	if c == nil {
		return nil
	}
	return c.SubApplication
}

func (c *CreatePaymentPreAuthorisationRequestRequest) GetBody() components.PaymentPreAuthorisationRequest {
	if c == nil {
		return components.PaymentPreAuthorisationRequest{}
	}
	return c.Body
}

type CreatePaymentPreAuthorisationRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfPreAuthorisationResponse *components.APIResponseOfPreAuthorisationResponse
	// Error Response
	APIResponseError *components.APIResponseError
}

func (c CreatePaymentPreAuthorisationRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreatePaymentPreAuthorisationRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreatePaymentPreAuthorisationRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreatePaymentPreAuthorisationRequestResponse) GetAPIResponseOfPreAuthorisationResponse() *components.APIResponseOfPreAuthorisationResponse {
	if c == nil {
		return nil
	}
	return c.APIResponseOfPreAuthorisationResponse
}

func (c *CreatePaymentPreAuthorisationRequestResponse) GetAPIResponseError() *components.APIResponseError {
	if c == nil {
		return nil
	}
	return c.APIResponseError
}
