// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type CreateVrpFundsConfirmationRequest struct {
	// The user's VRP [Consent Token](/getting-started/glossary#consent-token)
	Consent string                                 `header:"style=simple,explode=false,name=consent"`
	Body    components.VrpFundsConfirmationRequest `request:"mediaType=application/json"`
}

func (c *CreateVrpFundsConfirmationRequest) GetConsent() string {
	if c == nil {
		return ""
	}
	return c.Consent
}

func (c *CreateVrpFundsConfirmationRequest) GetBody() components.VrpFundsConfirmationRequest {
	if c == nil {
		return components.VrpFundsConfirmationRequest{}
	}
	return c.Body
}

type CreateVrpFundsConfirmationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfVrpFundsConfirmationResponse *components.APIResponseOfVrpFundsConfirmationResponse
	// Error Response
	APIErrorResponse *components.APIErrorResponse
}

func (c CreateVrpFundsConfirmationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateVrpFundsConfirmationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateVrpFundsConfirmationResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateVrpFundsConfirmationResponse) GetAPIResponseOfVrpFundsConfirmationResponse() *components.APIResponseOfVrpFundsConfirmationResponse {
	if c == nil {
		return nil
	}
	return c.APIResponseOfVrpFundsConfirmationResponse
}

func (c *CreateVrpFundsConfirmationResponse) GetAPIErrorResponse() *components.APIErrorResponse {
	if c == nil {
		return nil
	}
	return c.APIErrorResponse
}
