// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type CreateHostedConsentRequestRequest struct {
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string                               `header:"style=simple,explode=false,name=sub-application"`
	Body           components.CreateHostedConsentRequest `request:"mediaType=application/json"`
}

func (c *CreateHostedConsentRequestRequest) GetSubApplication() *string {
	if c == nil {
		return nil
	}
	return c.SubApplication
}

func (c *CreateHostedConsentRequestRequest) GetBody() components.CreateHostedConsentRequest {
	if c == nil {
		return components.CreateHostedConsentRequest{}
	}
	return c.Body
}

type CreateHostedConsentRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfCreateHostedConsentRequest *components.APIResponseOfCreateHostedConsentRequest
	// Bad Request
	APIErrorResponseV2 *components.APIErrorResponseV2
}

func (c CreateHostedConsentRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateHostedConsentRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateHostedConsentRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateHostedConsentRequestResponse) GetAPIResponseOfCreateHostedConsentRequest() *components.APIResponseOfCreateHostedConsentRequest {
	if c == nil {
		return nil
	}
	return c.APIResponseOfCreateHostedConsentRequest
}

func (c *CreateHostedConsentRequestResponse) GetAPIErrorResponseV2() *components.APIErrorResponseV2 {
	if c == nil {
		return nil
	}
	return c.APIErrorResponseV2
}
