// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type CreateEmbeddedPaymentAuthorisationRequest struct {
	// __Conditional__. Represents the user's login ID for the `Institution` to a personal account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuID *string `header:"style=simple,explode=false,name=psu-id"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a business account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuCorporateID *string `header:"style=simple,explode=false,name=psu-corporate-id"`
	// __Conditional__. The IP address of the PSU.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuIPAddress *string `header:"style=simple,explode=false,name=psu-ip-address"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string                                        `header:"style=simple,explode=false,name=sub-application"`
	Body           components.PaymentEmbeddedAuthorisationRequest `request:"mediaType=application/json"`
}

func (c *CreateEmbeddedPaymentAuthorisationRequest) GetPsuID() *string {
	if c == nil {
		return nil
	}
	return c.PsuID
}

func (c *CreateEmbeddedPaymentAuthorisationRequest) GetPsuCorporateID() *string {
	if c == nil {
		return nil
	}
	return c.PsuCorporateID
}

func (c *CreateEmbeddedPaymentAuthorisationRequest) GetPsuIPAddress() *string {
	if c == nil {
		return nil
	}
	return c.PsuIPAddress
}

func (c *CreateEmbeddedPaymentAuthorisationRequest) GetSubApplication() *string {
	if c == nil {
		return nil
	}
	return c.SubApplication
}

func (c *CreateEmbeddedPaymentAuthorisationRequest) GetBody() components.PaymentEmbeddedAuthorisationRequest {
	if c == nil {
		return components.PaymentEmbeddedAuthorisationRequest{}
	}
	return c.Body
}

type CreateEmbeddedPaymentAuthorisationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfPaymentEmbeddedAuthorisationRequestResponse *components.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse
	// Error Response
	APIResponseError *components.APIResponseError
}

func (c CreateEmbeddedPaymentAuthorisationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEmbeddedPaymentAuthorisationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEmbeddedPaymentAuthorisationResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEmbeddedPaymentAuthorisationResponse) GetAPIResponseOfPaymentEmbeddedAuthorisationRequestResponse() *components.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse {
	if c == nil {
		return nil
	}
	return c.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse
}

func (c *CreateEmbeddedPaymentAuthorisationResponse) GetAPIResponseError() *components.APIResponseError {
	if c == nil {
		return nil
	}
	return c.APIResponseError
}
