// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type DeleteRequest struct {
	// __Mandatory__. The consent Id of the `Consent` to update.
	ConsentID string `pathParam:"style=simple,explode=false,name=consentId"`
	// __Optional__. Whether to force the deletion.
	ForceDelete *bool `default:"true" queryParam:"style=form,explode=true,name=forceDelete"`
}

func (d DeleteRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteRequest) GetConsentID() string {
	if d == nil {
		return ""
	}
	return d.ConsentID
}

func (d *DeleteRequest) GetForceDelete() *bool {
	if d == nil {
		return nil
	}
	return d.ForceDelete
}

type DeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIResponseOfConsentDeleteResponse *components.APIResponseOfConsentDeleteResponse
	// Error Response
	APIResponseError *components.APIResponseError
}

func (d DeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteResponse) GetAPIResponseOfConsentDeleteResponse() *components.APIResponseOfConsentDeleteResponse {
	if d == nil {
		return nil
	}
	return d.APIResponseOfConsentDeleteResponse
}

func (d *DeleteResponse) GetAPIResponseError() *components.APIResponseError {
	if d == nil {
		return nil
	}
	return d.APIResponseError
}
