// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type DeleteWebhookRequest struct {
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
	// Registered webhook ID
	WebhookID string `pathParam:"style=simple,explode=false,name=webhook_id"`
}

func (d *DeleteWebhookRequest) GetSubApplication() *string {
	if d == nil {
		return nil
	}
	return d.SubApplication
}

func (d *DeleteWebhookRequest) GetWebhookID() string {
	if d == nil {
		return ""
	}
	return d.WebhookID
}

// DeleteWebhookResponseBody - Deleted
type DeleteWebhookResponseBody struct {
	Metadata *components.Metadata          `json:"metadata,omitzero"`
	Data     *components.RegisteredWebhook `json:"data,omitzero"`
}

func (d DeleteWebhookResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteWebhookResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteWebhookResponseBody) GetMetadata() *components.Metadata {
	if d == nil {
		return nil
	}
	return d.Metadata
}

func (d *DeleteWebhookResponseBody) GetData() *components.RegisteredWebhook {
	if d == nil {
		return nil
	}
	return d.Data
}

type DeleteWebhookResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Deleted
	Object *DeleteWebhookResponseBody
}

func (d DeleteWebhookResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteWebhookResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteWebhookResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteWebhookResponse) GetObject() *DeleteWebhookResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
