// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type DeleteUserBeneficiaryRequest struct {
	BeneficiaryID string `pathParam:"style=simple,explode=false,name=beneficiaryId"`
	UserID        string `pathParam:"style=simple,explode=false,name=userId"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
}

func (d *DeleteUserBeneficiaryRequest) GetBeneficiaryID() string {
	if d == nil {
		return ""
	}
	return d.BeneficiaryID
}

func (d *DeleteUserBeneficiaryRequest) GetUserID() string {
	if d == nil {
		return ""
	}
	return d.UserID
}

func (d *DeleteUserBeneficiaryRequest) GetSubApplication() *string {
	if d == nil {
		return nil
	}
	return d.SubApplication
}

type DeleteUserBeneficiaryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteUserBeneficiaryResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
