// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type ExtendConsentRequest struct {
	// __Mandatory__. The consent Id of the `Consent` to update.
	ConsentID string                          `pathParam:"style=simple,explode=false,name=consentId"`
	Body      components.ExtendConsentRequest `request:"mediaType=application/json"`
}

func (e *ExtendConsentRequest) GetConsentID() string {
	if e == nil {
		return ""
	}
	return e.ConsentID
}

func (e *ExtendConsentRequest) GetBody() components.ExtendConsentRequest {
	if e == nil {
		return components.ExtendConsentRequest{}
	}
	return e.Body
}

type ExtendConsentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfConsent *components.APIResponseOfConsent
	// Error Response. The supplied lastConfirmedAt date, Consent type, or Consent status is invalid.
	APIErrorResponse *components.APIErrorResponse
}

func (e ExtendConsentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *ExtendConsentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *ExtendConsentResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *ExtendConsentResponse) GetAPIResponseOfConsent() *components.APIResponseOfConsent {
	if e == nil {
		return nil
	}
	return e.APIResponseOfConsent
}

func (e *ExtendConsentResponse) GetAPIErrorResponse() *components.APIErrorResponse {
	if e == nil {
		return nil
	}
	return e.APIErrorResponse
}
