// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

// GetAccountConstraintsRulesByInstitutionEndpointMethod - The HTTP method that is associated with the operation for which constraints are to be retrieved
type GetAccountConstraintsRulesByInstitutionEndpointMethod string

const (
	GetAccountConstraintsRulesByInstitutionEndpointMethodPost   GetAccountConstraintsRulesByInstitutionEndpointMethod = "POST"
	GetAccountConstraintsRulesByInstitutionEndpointMethodPatch  GetAccountConstraintsRulesByInstitutionEndpointMethod = "PATCH"
	GetAccountConstraintsRulesByInstitutionEndpointMethodPut    GetAccountConstraintsRulesByInstitutionEndpointMethod = "PUT"
	GetAccountConstraintsRulesByInstitutionEndpointMethodGet    GetAccountConstraintsRulesByInstitutionEndpointMethod = "GET"
	GetAccountConstraintsRulesByInstitutionEndpointMethodDelete GetAccountConstraintsRulesByInstitutionEndpointMethod = "DELETE"
)

func (e GetAccountConstraintsRulesByInstitutionEndpointMethod) ToPointer() *GetAccountConstraintsRulesByInstitutionEndpointMethod {
	return &e
}
func (e *GetAccountConstraintsRulesByInstitutionEndpointMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "POST":
		fallthrough
	case "PATCH":
		fallthrough
	case "PUT":
		fallthrough
	case "GET":
		fallthrough
	case "DELETE":
		*e = GetAccountConstraintsRulesByInstitutionEndpointMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAccountConstraintsRulesByInstitutionEndpointMethod: %v", v)
	}
}

type GetAccountConstraintsRulesByInstitutionRequest struct {
	// Unique Id(s) of the `Institution`(s) to retrieve the Data Constraints for. Multiple institutionIds need to be separated by `,`
	InstitutionIds []string `queryParam:"style=form,explode=true,name=institutionIds"`
	// Country code of the `Institution`(s). Ensure that the country code matches the respective institutionIds; any mismatch will result in an HTTP 404 error response.
	InstitutionCountryCode string `queryParam:"style=form,explode=true,name=institutionCountryCode"`
	// The path on the API that is associated with the operation for which constraints are to be retrieved
	EndpointPath *string `queryParam:"style=form,explode=true,name=endpointPath"`
	// The HTTP method that is associated with the operation for which constraints are to be retrieved
	EndpointMethod *GetAccountConstraintsRulesByInstitutionEndpointMethod `queryParam:"style=form,explode=true,name=endpointMethod"`
}

func (g *GetAccountConstraintsRulesByInstitutionRequest) GetInstitutionIds() []string {
	if g == nil {
		return []string{}
	}
	return g.InstitutionIds
}

func (g *GetAccountConstraintsRulesByInstitutionRequest) GetInstitutionCountryCode() string {
	if g == nil {
		return ""
	}
	return g.InstitutionCountryCode
}

func (g *GetAccountConstraintsRulesByInstitutionRequest) GetEndpointPath() *string {
	if g == nil {
		return nil
	}
	return g.EndpointPath
}

func (g *GetAccountConstraintsRulesByInstitutionRequest) GetEndpointMethod() *GetAccountConstraintsRulesByInstitutionEndpointMethod {
	if g == nil {
		return nil
	}
	return g.EndpointMethod
}

type GetAccountConstraintsRulesByInstitutionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIListResponseOfDataConstraints *components.APIListResponseOfDataConstraints
}

func (g GetAccountConstraintsRulesByInstitutionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAccountConstraintsRulesByInstitutionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAccountConstraintsRulesByInstitutionResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAccountConstraintsRulesByInstitutionResponse) GetAPIListResponseOfDataConstraints() *components.APIListResponseOfDataConstraints {
	if g == nil {
		return nil
	}
	return g.APIListResponseOfDataConstraints
}
