// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetApplicationVRPConfigurationByApplicationIDRequest struct {
	// The id of the application that vrp configuration being created for
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
}

func (g *GetApplicationVRPConfigurationByApplicationIDRequest) GetApplicationID() string {
	if g == nil {
		return ""
	}
	return g.ApplicationID
}

type GetApplicationVRPConfigurationByApplicationIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Application vrp configuration was successfully fetched
	VrpConfiguration *components.VrpConfiguration
}

func (g GetApplicationVRPConfigurationByApplicationIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetApplicationVRPConfigurationByApplicationIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetApplicationVRPConfigurationByApplicationIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetApplicationVRPConfigurationByApplicationIDResponse) GetVrpConfiguration() *components.VrpConfiguration {
	if g == nil {
		return nil
	}
	return g.VrpConfiguration
}
