// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetApplicationByIDRequest struct {
	// The id of the application being fetched
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
}

func (g *GetApplicationByIDRequest) GetApplicationID() string {
	if g == nil {
		return ""
	}
	return g.ApplicationID
}

type GetApplicationByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Application was successfully fetched
	APIResponseOfApplicationResponse *components.APIResponseOfApplicationResponse
}

func (g GetApplicationByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetApplicationByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetApplicationByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetApplicationByIDResponse) GetAPIResponseOfApplicationResponse() *components.APIResponseOfApplicationResponse {
	if g == nil {
		return nil
	}
	return g.APIResponseOfApplicationResponse
}
