// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetBeneficiariesRequest struct {
	// __Mandatory__. The account Id of the user's bank account.
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
	// __Mandatory__. The `consent-token` containing the user's authorisation to make the request.
	Consent string `header:"style=simple,explode=false,name=consent"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
}

func (g *GetBeneficiariesRequest) GetAccountID() string {
	if g == nil {
		return ""
	}
	return g.AccountID
}

func (g *GetBeneficiariesRequest) GetConsent() string {
	if g == nil {
		return ""
	}
	return g.Consent
}

func (g *GetBeneficiariesRequest) GetSubApplication() *string {
	if g == nil {
		return nil
	}
	return g.SubApplication
}

type GetBeneficiariesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIListResponseOfBeneficiary *components.APIListResponseOfBeneficiary
	// Error Response
	APIResponseError *components.APIResponseError
}

func (g GetBeneficiariesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetBeneficiariesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetBeneficiariesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetBeneficiariesResponse) GetAPIListResponseOfBeneficiary() *components.APIListResponseOfBeneficiary {
	if g == nil {
		return nil
	}
	return g.APIListResponseOfBeneficiary
}

func (g *GetBeneficiariesResponse) GetAPIResponseError() *components.APIResponseError {
	if g == nil {
		return nil
	}
	return g.APIResponseError
}
