// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetConsentByIDRequest struct {
	// __Mandatory__. The consent Id of the `Consent` to update.
	ConsentID string `pathParam:"style=simple,explode=false,name=consentId"`
}

func (g *GetConsentByIDRequest) GetConsentID() string {
	if g == nil {
		return ""
	}
	return g.ConsentID
}

type GetConsentByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIResponseOfConsent *components.APIResponseOfConsent
	// Error Response
	APIResponseError *components.APIResponseError
}

func (g GetConsentByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetConsentByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetConsentByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetConsentByIDResponse) GetAPIResponseOfConsent() *components.APIResponseOfConsent {
	if g == nil {
		return nil
	}
	return g.APIResponseOfConsent
}

func (g *GetConsentByIDResponse) GetAPIResponseError() *components.APIResponseError {
	if g == nil {
		return nil
	}
	return g.APIResponseError
}
