// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetCategorisationAccountTypeRequest struct {
	// type of bank account (consumer or business)
	AccountType string `pathParam:"style=simple,explode=false,name=accountType"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
}

func (g *GetCategorisationAccountTypeRequest) GetAccountType() string {
	if g == nil {
		return ""
	}
	return g.AccountType
}

func (g *GetCategorisationAccountTypeRequest) GetSubApplication() *string {
	if g == nil {
		return nil
	}
	return g.SubApplication
}

type GetCategorisationAccountTypeMeta struct {
	TracingID *string `json:"tracingId,omitzero"`
}

func (g *GetCategorisationAccountTypeMeta) GetTracingID() *string {
	if g == nil {
		return nil
	}
	return g.TracingID
}

// GetCategorisationAccountTypeResponseBody - OK
type GetCategorisationAccountTypeResponseBody struct {
	Meta *GetCategorisationAccountTypeMeta `json:"meta,omitzero"`
	Data *components.GetCategoriesResponse `json:"data,omitzero"`
}

func (g GetCategorisationAccountTypeResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCategorisationAccountTypeResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCategorisationAccountTypeResponseBody) GetMeta() *GetCategorisationAccountTypeMeta {
	if g == nil {
		return nil
	}
	return g.Meta
}

func (g *GetCategorisationAccountTypeResponseBody) GetData() *components.GetCategoriesResponse {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetCategorisationAccountTypeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	Object *GetCategorisationAccountTypeResponseBody
}

func (g GetCategorisationAccountTypeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCategorisationAccountTypeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCategorisationAccountTypeResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCategorisationAccountTypeResponse) GetObject() *GetCategorisationAccountTypeResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
