// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetEventSubscriptionByIDRequest struct {
	// Unique identifier of the event type (for which notifications will be sent).
	EventTypeID string `pathParam:"style=simple,explode=false,name=eventTypeId"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
}

func (g *GetEventSubscriptionByIDRequest) GetEventTypeID() string {
	if g == nil {
		return ""
	}
	return g.EventTypeID
}

func (g *GetEventSubscriptionByIDRequest) GetSubApplication() *string {
	if g == nil {
		return nil
	}
	return g.SubApplication
}

type GetEventSubscriptionByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Event subscription data found
	APIResponseOfEventSubscriptionResponse *components.APIResponseOfEventSubscriptionResponse
}

func (g GetEventSubscriptionByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEventSubscriptionByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEventSubscriptionByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEventSubscriptionByIDResponse) GetAPIResponseOfEventSubscriptionResponse() *components.APIResponseOfEventSubscriptionResponse {
	if g == nil {
		return nil
	}
	return g.APIResponseOfEventSubscriptionResponse
}
