// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetHostedPaymentRequestRequest struct {
	// Unique Identifier of the payment request
	PaymentRequestID string `pathParam:"style=simple,explode=false,name=paymentRequestId"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
}

func (g *GetHostedPaymentRequestRequest) GetPaymentRequestID() string {
	if g == nil {
		return ""
	}
	return g.PaymentRequestID
}

func (g *GetHostedPaymentRequestRequest) GetSubApplication() *string {
	if g == nil {
		return nil
	}
	return g.SubApplication
}

type GetHostedPaymentRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIResponseOfGetHostedPaymentRequest *components.APIResponseOfGetHostedPaymentRequest
	// Unauthorized
	APIErrorResponseV2 *components.APIErrorResponseV2
}

func (g GetHostedPaymentRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetHostedPaymentRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetHostedPaymentRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetHostedPaymentRequestResponse) GetAPIResponseOfGetHostedPaymentRequest() *components.APIResponseOfGetHostedPaymentRequest {
	if g == nil {
		return nil
	}
	return g.APIResponseOfGetHostedPaymentRequest
}

func (g *GetHostedPaymentRequestResponse) GetAPIErrorResponseV2() *components.APIErrorResponseV2 {
	if g == nil {
		return nil
	}
	return g.APIErrorResponseV2
}
