// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetInstitutionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIListResponseOfInstitution *components.APIListResponseOfInstitution
	// Error Response
	APIResponseError *components.APIResponseError
}

func (g GetInstitutionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInstitutionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInstitutionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInstitutionsResponse) GetAPIListResponseOfInstitution() *components.APIListResponseOfInstitution {
	if g == nil {
		return nil
	}
	return g.APIListResponseOfInstitution
}

func (g *GetInstitutionsResponse) GetAPIResponseError() *components.APIResponseError {
	if g == nil {
		return nil
	}
	return g.APIResponseError
}
