// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetInstitutionRequest struct {
	// __Mandatory__. The Yapily institution Id for the `Institution`.
	InstitutionID string `pathParam:"style=simple,explode=false,name=institutionId"`
}

func (g *GetInstitutionRequest) GetInstitutionID() string {
	if g == nil {
		return ""
	}
	return g.InstitutionID
}

type GetInstitutionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	Institution *components.Institution
	// Error Response
	APIResponseError *components.APIResponseError
}

func (g GetInstitutionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInstitutionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInstitutionResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInstitutionResponse) GetInstitution() *components.Institution {
	if g == nil {
		return nil
	}
	return g.Institution
}

func (g *GetInstitutionResponse) GetAPIResponseError() *components.APIResponseError {
	if g == nil {
		return nil
	}
	return g.APIResponseError
}
