// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetStatementsRequest struct {
	// __Mandatory__. The `consent-token` containing the user's authorisation to make the request.
	Consent string `header:"style=simple,explode=false,name=consent"`
	// __Mandatory__. The account Id of the user's bank account.
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
	// __Optional__. Returned transactions will be on or after this date (yyyy-MM-dd'T'HH:mm:ss.SSSZ).
	From *string `queryParam:"style=form,explode=true,name=from"`
	// __Optional__. Returned transactions will be on or before this date (yyyy-MM-dd'T'HH:mm:ss.SSSZ).
	Before *string `queryParam:"style=form,explode=true,name=before"`
	// __Optional__. The maximum number of transaction records to be returned. Must be between 1 and 1000.
	Limit *int `queryParam:"style=form,explode=true,name=limit"`
	// __Optional__. Sort transaction records by date ascending with 'date' or descending with '-date'. The default sort order is descending
	Sort *components.SortEnum `queryParam:"style=form,explode=true,name=sort"`
	// __Optional__. The number of transaction records to be skipped. Used primarily with paginated results.
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
}

func (g *GetStatementsRequest) GetConsent() string {
	if g == nil {
		return ""
	}
	return g.Consent
}

func (g *GetStatementsRequest) GetAccountID() string {
	if g == nil {
		return ""
	}
	return g.AccountID
}

func (g *GetStatementsRequest) GetSubApplication() *string {
	if g == nil {
		return nil
	}
	return g.SubApplication
}

func (g *GetStatementsRequest) GetFrom() *string {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetStatementsRequest) GetBefore() *string {
	if g == nil {
		return nil
	}
	return g.Before
}

func (g *GetStatementsRequest) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetStatementsRequest) GetSort() *components.SortEnum {
	if g == nil {
		return nil
	}
	return g.Sort
}

func (g *GetStatementsRequest) GetOffset() *int {
	if g == nil {
		return nil
	}
	return g.Offset
}

type GetStatementsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIListResponseOfAccountStatement *components.APIListResponseOfAccountStatement
	// Error Response
	APIResponseError *components.APIResponseError
}

func (g GetStatementsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetStatementsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetStatementsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetStatementsResponse) GetAPIListResponseOfAccountStatement() *components.APIListResponseOfAccountStatement {
	if g == nil {
		return nil
	}
	return g.APIListResponseOfAccountStatement
}

func (g *GetStatementsResponse) GetAPIResponseError() *components.APIResponseError {
	if g == nil {
		return nil
	}
	return g.APIResponseError
}
