// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetSweepingVrpConsentByIDRequest struct {
	// The Consent ID to retrieve.
	ConsentID string `pathParam:"style=simple,explode=false,name=consentId"`
}

func (g *GetSweepingVrpConsentByIDRequest) GetConsentID() string {
	if g == nil {
		return ""
	}
	return g.ConsentID
}

type GetSweepingVrpConsentByIDResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	APIResponseOfVrpSweepingAuthorisationResponse *components.APIResponseOfVrpSweepingAuthorisationResponse
	// Error Response
	APIErrorResponse *components.APIErrorResponse
}

func (g GetSweepingVrpConsentByIDResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSweepingVrpConsentByIDResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSweepingVrpConsentByIDResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSweepingVrpConsentByIDResponse) GetAPIResponseOfVrpSweepingAuthorisationResponse() *components.APIResponseOfVrpSweepingAuthorisationResponse {
	if g == nil {
		return nil
	}
	return g.APIResponseOfVrpSweepingAuthorisationResponse
}

func (g *GetSweepingVrpConsentByIDResponse) GetAPIErrorResponse() *components.APIErrorResponse {
	if g == nil {
		return nil
	}
	return g.APIErrorResponse
}
