// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetTransactionsRequest struct {
	// __Mandatory__. The account Id of the user's bank account.
	AccountID string `pathParam:"style=simple,explode=false,name=accountId"`
	// __Mandatory__. The `consent-token` containing the user's authorisation to make the request.
	Consent string `header:"style=simple,explode=false,name=consent"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a personal account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuID *string `header:"style=simple,explode=false,name=psu-id"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a business account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuCorporateID *string `header:"style=simple,explode=false,name=psu-corporate-id"`
	// __Conditional__. The IP address of the PSU.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuIPAddress *string `header:"style=simple,explode=false,name=psu-ip-address"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
	// __Optional__. Returned transactions will be on or after this date (yyyy-MM-dd'T'HH:mm:ss.SSSZ).
	From *string `queryParam:"style=form,explode=true,name=from"`
	// __Optional__. Returned transactions will be on or before this date (yyyy-MM-dd'T'HH:mm:ss.SSSZ).
	Before *string `queryParam:"style=form,explode=true,name=before"`
	// __Optional__. The maximum number of transaction records to be returned. Must be between 1 and 1000.
	Limit *int `queryParam:"style=form,explode=true,name=limit"`
	// __Optional__. Sort transaction records by date ascending with 'date' or descending with '-date'. The default sort order is descending
	Sort *components.SortEnum `queryParam:"style=form,explode=true,name=sort"`
	// __Optional__. The number of transaction records to be skipped. Used primarily with paginated results.
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
	// __Optional__. This property is not currently in use.
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
}

func (g *GetTransactionsRequest) GetAccountID() string {
	if g == nil {
		return ""
	}
	return g.AccountID
}

func (g *GetTransactionsRequest) GetConsent() string {
	if g == nil {
		return ""
	}
	return g.Consent
}

func (g *GetTransactionsRequest) GetPsuID() *string {
	if g == nil {
		return nil
	}
	return g.PsuID
}

func (g *GetTransactionsRequest) GetPsuCorporateID() *string {
	if g == nil {
		return nil
	}
	return g.PsuCorporateID
}

func (g *GetTransactionsRequest) GetPsuIPAddress() *string {
	if g == nil {
		return nil
	}
	return g.PsuIPAddress
}

func (g *GetTransactionsRequest) GetSubApplication() *string {
	if g == nil {
		return nil
	}
	return g.SubApplication
}

func (g *GetTransactionsRequest) GetFrom() *string {
	if g == nil {
		return nil
	}
	return g.From
}

func (g *GetTransactionsRequest) GetBefore() *string {
	if g == nil {
		return nil
	}
	return g.Before
}

func (g *GetTransactionsRequest) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetTransactionsRequest) GetSort() *components.SortEnum {
	if g == nil {
		return nil
	}
	return g.Sort
}

func (g *GetTransactionsRequest) GetOffset() *int {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetTransactionsRequest) GetCursor() *string {
	if g == nil {
		return nil
	}
	return g.Cursor
}

type GetTransactionsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIListResponseOfTransaction *components.APIListResponseOfTransaction
	// Error Response
	APIResponseError *components.APIResponseError
}

func (g GetTransactionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTransactionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTransactionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTransactionsResponse) GetAPIListResponseOfTransaction() *components.APIListResponseOfTransaction {
	if g == nil {
		return nil
	}
	return g.APIListResponseOfTransaction
}

func (g *GetTransactionsResponse) GetAPIResponseError() *components.APIResponseError {
	if g == nil {
		return nil
	}
	return g.APIResponseError
}
