// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetUserRequest struct {
	// __Mandatory__. The Yapily generated UUID for the user.
	UserUUID string `pathParam:"style=simple,explode=false,name=userUuid"`
}

func (g *GetUserRequest) GetUserUUID() string {
	if g == nil {
		return ""
	}
	return g.UserUUID
}

type GetUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	ApplicationUser *components.ApplicationUser
	// Error Response
	APIResponseError *components.APIResponseError
}

func (g GetUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUserResponse) GetApplicationUser() *components.ApplicationUser {
	if g == nil {
		return nil
	}
	return g.ApplicationUser
}

func (g *GetUserResponse) GetAPIResponseError() *components.APIResponseError {
	if g == nil {
		return nil
	}
	return g.APIResponseError
}
