// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetUsersRequest struct {
	// __Optional__. Filter records based on the list of `applicationUserId` users provided.
	FilterApplicationUserID []string `queryParam:"style=form,explode=true,name=filter[applicationUserId]"`
}

func (g GetUsersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUsersRequest) GetFilterApplicationUserID() []string {
	if g == nil {
		return nil
	}
	return g.FilterApplicationUserID
}

type GetUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	ApplicationUsers []components.ApplicationUser
	// Error Response
	APIResponseError *components.APIResponseError
}

func (g GetUsersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUsersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUsersResponse) GetApplicationUsers() []components.ApplicationUser {
	if g == nil {
		return nil
	}
	return g.ApplicationUsers
}

func (g *GetUsersResponse) GetAPIResponseError() *components.APIResponseError {
	if g == nil {
		return nil
	}
	return g.APIResponseError
}
