// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type GetVrpPaymentDetailsRequest struct {
	// __Mandatory__. The Payment Id of the `Variable Recurring Payments` to retrieve.
	PaymentID string `pathParam:"style=simple,explode=false,name=paymentId"`
	// __Mandatory__. The [Consent Token](/getting-started/glossary#consent-token) containing the user's authorisation to make the `Variable Recurring Payments` request.
	Consent string `header:"style=simple,explode=false,name=consent"`
}

func (g *GetVrpPaymentDetailsRequest) GetPaymentID() string {
	if g == nil {
		return ""
	}
	return g.PaymentID
}

func (g *GetVrpPaymentDetailsRequest) GetConsent() string {
	if g == nil {
		return ""
	}
	return g.Consent
}

type GetVrpPaymentDetailsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	APIResponseOfVrpSubmissionResponse *components.APIResponseOfVrpSubmissionResponse
	// Error Response
	APIErrorResponse *components.APIErrorResponse
}

func (g GetVrpPaymentDetailsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetVrpPaymentDetailsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetVrpPaymentDetailsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetVrpPaymentDetailsResponse) GetAPIResponseOfVrpSubmissionResponse() *components.APIResponseOfVrpSubmissionResponse {
	if g == nil {
		return nil
	}
	return g.APIResponseOfVrpSubmissionResponse
}

func (g *GetVrpPaymentDetailsResponse) GetAPIErrorResponse() *components.APIErrorResponse {
	if g == nil {
		return nil
	}
	return g.APIErrorResponse
}
