// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type InitiateAccountRequestRequest struct {
	// __Conditional__. Represents the user's login ID for the `Institution` to a personal account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuID *string `header:"style=simple,explode=false,name=psu-id"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a business account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuCorporateID *string `header:"style=simple,explode=false,name=psu-corporate-id"`
	// __Conditional__. The IP address of the PSU.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuIPAddress *string `header:"style=simple,explode=false,name=psu-ip-address"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string                                `header:"style=simple,explode=false,name=sub-application"`
	Body           components.AccountAuthorisationRequest `request:"mediaType=application/json"`
}

func (i *InitiateAccountRequestRequest) GetPsuID() *string {
	if i == nil {
		return nil
	}
	return i.PsuID
}

func (i *InitiateAccountRequestRequest) GetPsuCorporateID() *string {
	if i == nil {
		return nil
	}
	return i.PsuCorporateID
}

func (i *InitiateAccountRequestRequest) GetPsuIPAddress() *string {
	if i == nil {
		return nil
	}
	return i.PsuIPAddress
}

func (i *InitiateAccountRequestRequest) GetSubApplication() *string {
	if i == nil {
		return nil
	}
	return i.SubApplication
}

func (i *InitiateAccountRequestRequest) GetBody() components.AccountAuthorisationRequest {
	if i == nil {
		return components.AccountAuthorisationRequest{}
	}
	return i.Body
}

type InitiateAccountRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfAccountAuthorisationResponse *components.APIResponseOfAccountAuthorisationResponse
	// Error Response
	APIResponseError *components.APIResponseError
}

func (i InitiateAccountRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InitiateAccountRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InitiateAccountRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *InitiateAccountRequestResponse) GetAPIResponseOfAccountAuthorisationResponse() *components.APIResponseOfAccountAuthorisationResponse {
	if i == nil {
		return nil
	}
	return i.APIResponseOfAccountAuthorisationResponse
}

func (i *InitiateAccountRequestResponse) GetAPIResponseError() *components.APIResponseError {
	if i == nil {
		return nil
	}
	return i.APIResponseError
}
