// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type Amount struct {
	// __Mandatory__. Transaction money amount in cents (or equivalent). Positive amount implies money in, negative amount implies money out.
	Value int64 `json:"value"`
	// __Mandatory__. Transaction currency.
	Currency string `json:"currency"`
}

func (a *Amount) GetValue() int64 {
	if a == nil {
		return 0
	}
	return a.Value
}

func (a *Amount) GetCurrency() string {
	if a == nil {
		return ""
	}
	return a.Currency
}

type Merchant struct {
	// __Optional__. Merchant Category Code (MCC) according to ISO 18245
	Mcc *string `json:"mcc,omitzero"`
}

func (m *Merchant) GetMcc() *string {
	if m == nil {
		return nil
	}
	return m.Mcc
}

type Transaction struct {
	// __Mandatory__. A globally unique transaction ID.
	ID string `json:"id"`
	// __Mandatory__. Transaction date in ISO 8601 format (eg. 2025-01-01T12:59:59.999Z)
	Date     string    `json:"date"`
	Amount   Amount    `json:"amount"`
	Merchant *Merchant `json:"merchant,omitzero"`
	// __Mandatory__. Transaction-specific description.
	Description string `json:"description"`
	// __Mandatory__. Transaction-specific two-letter country code in ISO 3166-1 alpha-2 format (e.g. GB)
	CountryCode string `json:"countryCode"`
}

func (t Transaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *Transaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *Transaction) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *Transaction) GetDate() string {
	if t == nil {
		return ""
	}
	return t.Date
}

func (t *Transaction) GetAmount() Amount {
	if t == nil {
		return Amount{}
	}
	return t.Amount
}

func (t *Transaction) GetMerchant() *Merchant {
	if t == nil {
		return nil
	}
	return t.Merchant
}

func (t *Transaction) GetDescription() string {
	if t == nil {
		return ""
	}
	return t.Description
}

func (t *Transaction) GetCountryCode() string {
	if t == nil {
		return ""
	}
	return t.CountryCode
}

type PostTransactionsCategorisationRequestBody struct {
	// __Mandatory__. Two-letter country code in ISO 3166-1 alpha-2 format (e.g. GB)
	CountryCode string `json:"countryCode"`
	// __Mandatory__. Allowed values are `consumer` and `business`.
	CategorisationType string        `json:"categorisationType"`
	Transactions       []Transaction `json:"transactions"`
}

func (p *PostTransactionsCategorisationRequestBody) GetCountryCode() string {
	if p == nil {
		return ""
	}
	return p.CountryCode
}

func (p *PostTransactionsCategorisationRequestBody) GetCategorisationType() string {
	if p == nil {
		return ""
	}
	return p.CategorisationType
}

func (p *PostTransactionsCategorisationRequestBody) GetTransactions() []Transaction {
	if p == nil {
		return []Transaction{}
	}
	return p.Transactions
}

type PostTransactionsCategorisationRequest struct {
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string                                    `header:"style=simple,explode=false,name=sub-application"`
	Body           *PostTransactionsCategorisationRequestBody `request:"mediaType=application/json"`
}

func (p PostTransactionsCategorisationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostTransactionsCategorisationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostTransactionsCategorisationRequest) GetSubApplication() *string {
	if p == nil {
		return nil
	}
	return p.SubApplication
}

func (p *PostTransactionsCategorisationRequest) GetBody() *PostTransactionsCategorisationRequestBody {
	if p == nil {
		return nil
	}
	return p.Body
}

type PostTransactionsCategorisationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfCreateTransactionsCategorisationRequest *components.APIResponseOfCreateTransactionsCategorisationRequest
}

func (p PostTransactionsCategorisationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostTransactionsCategorisationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostTransactionsCategorisationResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostTransactionsCategorisationResponse) GetAPIResponseOfCreateTransactionsCategorisationRequest() *components.APIResponseOfCreateTransactionsCategorisationRequest {
	if p == nil {
		return nil
	}
	return p.APIResponseOfCreateTransactionsCategorisationRequest
}
