// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
	"time"
)

type PostAccountsAccountIDTransactionsCategorisationRequestBody struct {
	// __Mandatory__. Two-letter country code in ISO 3166-1 alpha-2 format (e.g. GB)
	CountryCode string `json:"countryCode"`
	// __Mandatory__. Allowed values are `consumer` and `business`.
	CategorisationType string `json:"categorisationType"`
	// __Optional__. Returned transactions will be on or after this date (yyyy-MM-dd'T'HH:mm:ss.SSSZ).
	From *time.Time `json:"from,omitzero"`
	// __Optional__. Returned transactions will be on or before this date (yyyy-MM-dd'T'HH:mm:ss.SSSZ).
	Before *time.Time `json:"before,omitzero"`
}

func (p PostAccountsAccountIDTransactionsCategorisationRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequestBody) GetCountryCode() string {
	if p == nil {
		return ""
	}
	return p.CountryCode
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequestBody) GetCategorisationType() string {
	if p == nil {
		return ""
	}
	return p.CategorisationType
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequestBody) GetFrom() *time.Time {
	if p == nil {
		return nil
	}
	return p.From
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequestBody) GetBefore() *time.Time {
	if p == nil {
		return nil
	}
	return p.Before
}

type PostAccountsAccountIDTransactionsCategorisationRequest struct {
	// __Mandatory__. The `consent-token` containing the user's authorisation to make the request.
	Consent string `header:"style=simple,explode=false,name=consent"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a personal account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuID *string `header:"style=simple,explode=false,name=psu-id"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a business account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuCorporateID *string `header:"style=simple,explode=false,name=psu-corporate-id"`
	// __Conditional__. The IP address of the PSU.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuIPAddress *string `header:"style=simple,explode=false,name=psu-ip-address"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string `header:"style=simple,explode=false,name=sub-application"`
	// Unique identifier for account
	AccountID string                                                      `pathParam:"style=simple,explode=false,name=accountId"`
	Body      *PostAccountsAccountIDTransactionsCategorisationRequestBody `request:"mediaType=application/json"`
}

func (p PostAccountsAccountIDTransactionsCategorisationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequest) GetConsent() string {
	if p == nil {
		return ""
	}
	return p.Consent
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequest) GetPsuID() *string {
	if p == nil {
		return nil
	}
	return p.PsuID
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequest) GetPsuCorporateID() *string {
	if p == nil {
		return nil
	}
	return p.PsuCorporateID
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequest) GetPsuIPAddress() *string {
	if p == nil {
		return nil
	}
	return p.PsuIPAddress
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequest) GetSubApplication() *string {
	if p == nil {
		return nil
	}
	return p.SubApplication
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequest) GetAccountID() string {
	if p == nil {
		return ""
	}
	return p.AccountID
}

func (p *PostAccountsAccountIDTransactionsCategorisationRequest) GetBody() *PostAccountsAccountIDTransactionsCategorisationRequestBody {
	if p == nil {
		return nil
	}
	return p.Body
}

type PostAccountsAccountIDTransactionsCategorisationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfCreateTransactionsCategorisationRequest *components.APIResponseOfCreateTransactionsCategorisationRequest
}

func (p PostAccountsAccountIDTransactionsCategorisationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostAccountsAccountIDTransactionsCategorisationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PostAccountsAccountIDTransactionsCategorisationResponse) GetHTTPMeta() components.HTTPMetadata {
	if p == nil {
		return components.HTTPMetadata{}
	}
	return p.HTTPMeta
}

func (p *PostAccountsAccountIDTransactionsCategorisationResponse) GetAPIResponseOfCreateTransactionsCategorisationRequest() *components.APIResponseOfCreateTransactionsCategorisationRequest {
	if p == nil {
		return nil
	}
	return p.APIResponseOfCreateTransactionsCategorisationRequest
}
