// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type UpdateApplicationRequest struct {
	// The id of the application being updated
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
	// The application to update
	Body components.ApplicationRequest `request:"mediaType=application/json"`
}

func (u *UpdateApplicationRequest) GetApplicationID() string {
	if u == nil {
		return ""
	}
	return u.ApplicationID
}

func (u *UpdateApplicationRequest) GetBody() components.ApplicationRequest {
	if u == nil {
		return components.ApplicationRequest{}
	}
	return u.Body
}

type UpdateApplicationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Application was successfully updated
	APIResponseOfApplicationResponse *components.APIResponseOfApplicationResponse
}

func (u UpdateApplicationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateApplicationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateApplicationResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateApplicationResponse) GetAPIResponseOfApplicationResponse() *components.APIResponseOfApplicationResponse {
	if u == nil {
		return nil
	}
	return u.APIResponseOfApplicationResponse
}
