// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type UpdateEmbeddedBulkPaymentAuthorisationRequest struct {
	// __Mandatory__. The consent Id of the `Consent` to update.
	ConsentID string `pathParam:"style=simple,explode=false,name=consentId"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a personal account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuID *string `header:"style=simple,explode=false,name=psu-id"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a business account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuCorporateID *string `header:"style=simple,explode=false,name=psu-corporate-id"`
	// __Conditional__. The IP address of the PSU.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuIPAddress *string                                            `header:"style=simple,explode=false,name=psu-ip-address"`
	Body         components.BulkPaymentEmbeddedAuthorisationRequest `request:"mediaType=application/json"`
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationRequest) GetConsentID() string {
	if u == nil {
		return ""
	}
	return u.ConsentID
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationRequest) GetPsuID() *string {
	if u == nil {
		return nil
	}
	return u.PsuID
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationRequest) GetPsuCorporateID() *string {
	if u == nil {
		return nil
	}
	return u.PsuCorporateID
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationRequest) GetPsuIPAddress() *string {
	if u == nil {
		return nil
	}
	return u.PsuIPAddress
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationRequest) GetBody() components.BulkPaymentEmbeddedAuthorisationRequest {
	if u == nil {
		return components.BulkPaymentEmbeddedAuthorisationRequest{}
	}
	return u.Body
}

type UpdateEmbeddedBulkPaymentAuthorisationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Ok
	APIResponseOfPaymentEmbeddedAuthorisationRequestResponse *components.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse
	// Error Response
	APIResponseError *components.APIResponseError
}

func (u UpdateEmbeddedBulkPaymentAuthorisationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationResponse) GetAPIResponseOfPaymentEmbeddedAuthorisationRequestResponse() *components.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse {
	if u == nil {
		return nil
	}
	return u.APIResponseOfPaymentEmbeddedAuthorisationRequestResponse
}

func (u *UpdateEmbeddedBulkPaymentAuthorisationResponse) GetAPIResponseError() *components.APIResponseError {
	if u == nil {
		return nil
	}
	return u.APIResponseError
}
