// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type UpdateEmbeddedAccountRequestRequest struct {
	// __Mandatory__. The consent Id of the `Consent` to update.
	ConsentID string `pathParam:"style=simple,explode=false,name=consentId"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a personal account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuID *string `header:"style=simple,explode=false,name=psu-id"`
	// __Conditional__. Represents the user's login ID for the `Institution` to a business account.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuCorporateID *string `header:"style=simple,explode=false,name=psu-corporate-id"`
	// __Conditional__. The IP address of the PSU.
	//
	// See [PSU identifiers](/open-banking-flow/user-authorisation/psu-identifiers) to see if this header is required.
	PsuIPAddress *string `header:"style=simple,explode=false,name=psu-ip-address"`
	// The sub-application ID to which event type is being subscribed to
	SubApplication *string                                        `header:"style=simple,explode=false,name=sub-application"`
	Body           components.EmbeddedAccountAuthorisationRequest `request:"mediaType=application/json"`
}

func (u *UpdateEmbeddedAccountRequestRequest) GetConsentID() string {
	if u == nil {
		return ""
	}
	return u.ConsentID
}

func (u *UpdateEmbeddedAccountRequestRequest) GetPsuID() *string {
	if u == nil {
		return nil
	}
	return u.PsuID
}

func (u *UpdateEmbeddedAccountRequestRequest) GetPsuCorporateID() *string {
	if u == nil {
		return nil
	}
	return u.PsuCorporateID
}

func (u *UpdateEmbeddedAccountRequestRequest) GetPsuIPAddress() *string {
	if u == nil {
		return nil
	}
	return u.PsuIPAddress
}

func (u *UpdateEmbeddedAccountRequestRequest) GetSubApplication() *string {
	if u == nil {
		return nil
	}
	return u.SubApplication
}

func (u *UpdateEmbeddedAccountRequestRequest) GetBody() components.EmbeddedAccountAuthorisationRequest {
	if u == nil {
		return components.EmbeddedAccountAuthorisationRequest{}
	}
	return u.Body
}

type UpdateEmbeddedAccountRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	APIResponseOfEmbeddedAccountAuthorisationResponse *components.APIResponseOfEmbeddedAccountAuthorisationResponse
	// Error Response
	APIResponseError *components.APIResponseError
}

func (u UpdateEmbeddedAccountRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateEmbeddedAccountRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateEmbeddedAccountRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateEmbeddedAccountRequestResponse) GetAPIResponseOfEmbeddedAccountAuthorisationResponse() *components.APIResponseOfEmbeddedAccountAuthorisationResponse {
	if u == nil {
		return nil
	}
	return u.APIResponseOfEmbeddedAccountAuthorisationResponse
}

func (u *UpdateEmbeddedAccountRequestResponse) GetAPIResponseError() *components.APIResponseError {
	if u == nil {
		return nil
	}
	return u.APIResponseError
}
