// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type AccountAuthorisationRequest struct {
	// `User` for which the authorisation request was created.
	UserUUID *string `json:"userUuid,omitzero"`
	// __Conditional__. User-friendly identifier of the `User` that provides authorisation. If a `User` with the specified `applicationUserId` exists, it will be used otherwise, a new `User` with the specified `applicationUserId` will be created and used. Either the `userUuid` or `applicationUserId` must be provided.
	ApplicationUserID *string `json:"applicationUserId,omitzero"`
	// Extra parameters the TPP may want to get forwarded in the callback request after the PSU redirect.
	ForwardParameters []string `json:"forwardParameters,omitzero"`
	// __Mandatory__. The reference to the `Institution` which identifies which institution the authorisation request is sent to.
	InstitutionID string `json:"institutionId"`
	// __Optional__. The server to redirect the user to after the user completes the authorisation at the `Institution`.
	//
	// See [Using a callback (Optional)](/open-banking-flow/handling-redirects/callback-url) for more information.
	Callback *string `json:"callback,omitzero"`
	// __Optional__. The server to redirect the user to after the user complete the authorisation at the `Institution`.
	Redirect *RedirectRequest `json:"redirect,omitzero"`
	// __Conditional__. Used to receive a `oneTimeToken` rather than a `consentToken` at the `callback` for additional security. This can only be used when the `callback` is set.
	//
	// See [Using a callback with an OTT (Optional)](/open-banking-flow/handling-redirects/callback-url) for more information.
	OneTimeToken *bool `json:"oneTimeToken,omitzero"`
	// __Conditional__. Used to further specify details of the `Consent` to request
	//
	// Conditions:
	//
	// 1. Mandatory to specify the individual scopes to request from the user at the `Institution` for an account authorisation
	// 2. Mandatory to specify an expiry time on the created `Consent` at which time will render it unusable
	// 3. Mandatory to specify the date range that the created `Consent` will be able to access transactions for (given the range is support for the `Institution`)
	AccountRequest *AccountRequest `json:"accountRequest,omitzero"`
}

func (a AccountAuthorisationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountAuthorisationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountAuthorisationRequest) GetUserUUID() *string {
	if a == nil {
		return nil
	}
	return a.UserUUID
}

func (a *AccountAuthorisationRequest) GetApplicationUserID() *string {
	if a == nil {
		return nil
	}
	return a.ApplicationUserID
}

func (a *AccountAuthorisationRequest) GetForwardParameters() []string {
	if a == nil {
		return nil
	}
	return a.ForwardParameters
}

func (a *AccountAuthorisationRequest) GetInstitutionID() string {
	if a == nil {
		return ""
	}
	return a.InstitutionID
}

func (a *AccountAuthorisationRequest) GetCallback() *string {
	if a == nil {
		return nil
	}
	return a.Callback
}

func (a *AccountAuthorisationRequest) GetRedirect() *RedirectRequest {
	if a == nil {
		return nil
	}
	return a.Redirect
}

func (a *AccountAuthorisationRequest) GetOneTimeToken() *bool {
	if a == nil {
		return nil
	}
	return a.OneTimeToken
}

func (a *AccountAuthorisationRequest) GetAccountRequest() *AccountRequest {
	if a == nil {
		return nil
	}
	return a.AccountRequest
}
