// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

type AccountAuthorisationResponse struct {
	// Unique identifier for the account authorisation request.
	//
	// The `consentID` used to [retrieve a consent](/api/reference/#operation/getConsentById).
	ID *string `json:"id,omitzero"`
	// The `User` that the authorisation request was created for.
	UserUUID *string `json:"userUuid,omitzero"`
	// The user-friendly reference to the `User` that the authorisation request was created for.
	ApplicationUserID *string `json:"applicationUserId,omitzero"`
	ReferenceID       *string `json:"referenceId,omitzero"`
	// The `Institution` the authorisation request was sent to.
	InstitutionID *string `json:"institutionId,omitzero"`
	// Current status of the embedded authorisation request in code form.
	Status *AuthorisationStatus `json:"status,omitzero"`
	// Date and time the consent was created.
	CreatedAt *time.Time `json:"createdAt,omitzero"`
	// When performing a transaction query using the consent, this is the earliest date of transaction records that can be retrieved.
	TransactionFrom *time.Time `json:"transactionFrom,omitzero"`
	// When performing a transaction query using the consent, this is the latest date of transaction records that can be retrieved.
	TransactionTo *time.Time `json:"transactionTo,omitzero"`
	// Date and time the authorisation expires. Re-authorisation is needed to retain access.
	ExpiresAt *time.Time `json:"expiresAt,omitzero"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TimeToExpireInMillis *int64  `json:"timeToExpireInMillis,omitzero"`
	TimeToExpire         *string `json:"timeToExpire,omitzero"`
	// The set of features the consent provides access to.
	FeatureScope []FeatureEnum `json:"featureScope,omitzero"`
	// Represents the authorisation to gain access to the requested features. Required to access account information.
	ConsentToken *string `json:"consentToken,omitzero"`
	// Correlation ID used with the `Institution` during the authorisation process.
	State *string `json:"state,omitzero"`
	// Date and time the request was authorised by the `Institution`.
	AuthorizedAt *time.Time `json:"authorizedAt,omitzero"`
	// The time the PSU last confirmed access to their account information, either through full authentication with the institution, or through reconfirmation with the TPP.
	LastConfirmedAt *time.Time `json:"lastConfirmedAt,omitzero"`
	// The date and time the consent must be reconfirmed by to ensure continued access to the account information.
	ReconfirmBy *time.Time `json:"reconfirmBy,omitzero"`
	// Unique identifier of the consent assigned by the `Institution`.
	InstitutionConsentID *string `json:"institutionConsentId,omitzero"`
	AuthorisationURL     *string `json:"authorisationUrl,omitzero"`
	// The URL link for the QR code that may be scanned via a mobile device to make an authorisation redirect to the bank (authURL encoded).
	QrCodeURL *string `json:"qrCodeUrl,omitzero"`
}

func (a AccountAuthorisationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountAuthorisationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountAuthorisationResponse) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AccountAuthorisationResponse) GetUserUUID() *string {
	if a == nil {
		return nil
	}
	return a.UserUUID
}

func (a *AccountAuthorisationResponse) GetApplicationUserID() *string {
	if a == nil {
		return nil
	}
	return a.ApplicationUserID
}

func (a *AccountAuthorisationResponse) GetReferenceID() *string {
	if a == nil {
		return nil
	}
	return a.ReferenceID
}

func (a *AccountAuthorisationResponse) GetInstitutionID() *string {
	if a == nil {
		return nil
	}
	return a.InstitutionID
}

func (a *AccountAuthorisationResponse) GetStatus() *AuthorisationStatus {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *AccountAuthorisationResponse) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AccountAuthorisationResponse) GetTransactionFrom() *time.Time {
	if a == nil {
		return nil
	}
	return a.TransactionFrom
}

func (a *AccountAuthorisationResponse) GetTransactionTo() *time.Time {
	if a == nil {
		return nil
	}
	return a.TransactionTo
}

func (a *AccountAuthorisationResponse) GetExpiresAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.ExpiresAt
}

func (a *AccountAuthorisationResponse) GetTimeToExpireInMillis() *int64 {
	if a == nil {
		return nil
	}
	return a.TimeToExpireInMillis
}

func (a *AccountAuthorisationResponse) GetTimeToExpire() *string {
	if a == nil {
		return nil
	}
	return a.TimeToExpire
}

func (a *AccountAuthorisationResponse) GetFeatureScope() []FeatureEnum {
	if a == nil {
		return nil
	}
	return a.FeatureScope
}

func (a *AccountAuthorisationResponse) GetConsentToken() *string {
	if a == nil {
		return nil
	}
	return a.ConsentToken
}

func (a *AccountAuthorisationResponse) GetState() *string {
	if a == nil {
		return nil
	}
	return a.State
}

func (a *AccountAuthorisationResponse) GetAuthorizedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.AuthorizedAt
}

func (a *AccountAuthorisationResponse) GetLastConfirmedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastConfirmedAt
}

func (a *AccountAuthorisationResponse) GetReconfirmBy() *time.Time {
	if a == nil {
		return nil
	}
	return a.ReconfirmBy
}

func (a *AccountAuthorisationResponse) GetInstitutionConsentID() *string {
	if a == nil {
		return nil
	}
	return a.InstitutionConsentID
}

func (a *AccountAuthorisationResponse) GetAuthorisationURL() *string {
	if a == nil {
		return nil
	}
	return a.AuthorisationURL
}

func (a *AccountAuthorisationResponse) GetQrCodeURL() *string {
	if a == nil {
		return nil
	}
	return a.QrCodeURL
}
