// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountName struct {
	// The bank account holder's name given by the account owner.
	Name *string `json:"name,omitzero"`
}

func (a *AccountName) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}
