// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type AccountIdentifierType string

const (
	AccountIdentifierTypeIban AccountIdentifierType = "IBAN"
)

func (e AccountIdentifierType) ToPointer() *AccountIdentifierType {
	return &e
}
func (e *AccountIdentifierType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IBAN":
		*e = AccountIdentifierType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccountIdentifierType: %v", v)
	}
}
