// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountIdentificationType - __Mandatory__. Used to describe the format of the account.
//
//	See [Account Identification Combinations](/payments/payment-resources/intro-to-payment-execution#account-identifications-combinations) for more information on when to specify each type.
type AccountIdentificationType string

const (
	AccountIdentificationTypeSortCode         AccountIdentificationType = "SORT_CODE"
	AccountIdentificationTypeAccountNumber    AccountIdentificationType = "ACCOUNT_NUMBER"
	AccountIdentificationTypeIban             AccountIdentificationType = "IBAN"
	AccountIdentificationTypeBban             AccountIdentificationType = "BBAN"
	AccountIdentificationTypeBic              AccountIdentificationType = "BIC"
	AccountIdentificationTypePan              AccountIdentificationType = "PAN"
	AccountIdentificationTypeMaskedPan        AccountIdentificationType = "MASKED_PAN"
	AccountIdentificationTypeMsisdn           AccountIdentificationType = "MSISDN"
	AccountIdentificationTypeBsb              AccountIdentificationType = "BSB"
	AccountIdentificationTypeNcc              AccountIdentificationType = "NCC"
	AccountIdentificationTypeAba              AccountIdentificationType = "ABA"
	AccountIdentificationTypeAbaWire          AccountIdentificationType = "ABA_WIRE"
	AccountIdentificationTypeAbaAch           AccountIdentificationType = "ABA_ACH"
	AccountIdentificationTypeEmail            AccountIdentificationType = "EMAIL"
	AccountIdentificationTypeRollNumber       AccountIdentificationType = "ROLL_NUMBER"
	AccountIdentificationTypeBlz              AccountIdentificationType = "BLZ"
	AccountIdentificationTypeIfs              AccountIdentificationType = "IFS"
	AccountIdentificationTypeClabe            AccountIdentificationType = "CLABE"
	AccountIdentificationTypeCtn              AccountIdentificationType = "CTN"
	AccountIdentificationTypeBranchCode       AccountIdentificationType = "BRANCH_CODE"
	AccountIdentificationTypeVirtualAccountID AccountIdentificationType = "VIRTUAL_ACCOUNT_ID"
)

func (e AccountIdentificationType) ToPointer() *AccountIdentificationType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountIdentificationType) IsExact() bool {
	if e != nil {
		switch *e {
		case "SORT_CODE", "ACCOUNT_NUMBER", "IBAN", "BBAN", "BIC", "PAN", "MASKED_PAN", "MSISDN", "BSB", "NCC", "ABA", "ABA_WIRE", "ABA_ACH", "EMAIL", "ROLL_NUMBER", "BLZ", "IFS", "CLABE", "CTN", "BRANCH_CODE", "VIRTUAL_ACCOUNT_ID":
			return true
		}
	}
	return false
}
