// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AccountIdentification struct {
	// __Mandatory__. Used to describe the format of the account.
	//
	//  See [Account Identification Combinations](/payments/payment-resources/intro-to-payment-execution#account-identifications-combinations) for more information on when to specify each type.
	Type AccountIdentificationType `json:"type"`
	// __Mandatory__. The value associated with the account identification type.
	//
	//  See [Account Identification Combinations](/payments/payment-resources/intro-to-payment-execution#account-identifications-combinations) for more information on the format of the values.
	Identification string `json:"identification"`
}

func (a *AccountIdentification) GetType() AccountIdentificationType {
	if a == nil {
		return AccountIdentificationType("")
	}
	return a.Type
}

func (a *AccountIdentification) GetIdentification() string {
	if a == nil {
		return ""
	}
	return a.Identification
}
