// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AccountType - The type of account e.g. (Credit Card, Savings).
type AccountType string

const (
	AccountTypeCashTrading                    AccountType = "CASH_TRADING"
	AccountTypeCashIncome                     AccountType = "CASH_INCOME"
	AccountTypeCashPayment                    AccountType = "CASH_PAYMENT"
	AccountTypeChargeCard                     AccountType = "CHARGE_CARD"
	AccountTypeCharges                        AccountType = "CHARGES"
	AccountTypeCommission                     AccountType = "COMMISSION"
	AccountTypeCreditCard                     AccountType = "CREDIT_CARD"
	AccountTypeCurrent                        AccountType = "CURRENT"
	AccountTypeEMoney                         AccountType = "E_MONEY"
	AccountTypeLimitedLiquiditySavingsAccount AccountType = "LIMITED_LIQUIDITY_SAVINGS_ACCOUNT"
	AccountTypeLoan                           AccountType = "LOAN"
	AccountTypeMarginalLending                AccountType = "MARGINAL_LENDING"
	AccountTypeMoneyMarket                    AccountType = "MONEY_MARKET"
	AccountTypeMortgage                       AccountType = "MORTGAGE"
	AccountTypeNonResidentExternal            AccountType = "NON_RESIDENT_EXTERNAL"
	AccountTypeOther                          AccountType = "OTHER"
	AccountTypeOverdraft                      AccountType = "OVERDRAFT"
	AccountTypeOvernightDeposit               AccountType = "OVERNIGHT_DEPOSIT"
	AccountTypePrepaidCard                    AccountType = "PREPAID_CARD"
	AccountTypeSalary                         AccountType = "SALARY"
	AccountTypeSavings                        AccountType = "SAVINGS"
	AccountTypeSettlement                     AccountType = "SETTLEMENT"
	AccountTypeTax                            AccountType = "TAX"
	AccountTypeUnknown                        AccountType = "UNKNOWN"
)

func (e AccountType) ToPointer() *AccountType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AccountType) IsExact() bool {
	if e != nil {
		switch *e {
		case "CASH_TRADING", "CASH_INCOME", "CASH_PAYMENT", "CHARGE_CARD", "CHARGES", "COMMISSION", "CREDIT_CARD", "CURRENT", "E_MONEY", "LIMITED_LIQUIDITY_SAVINGS_ACCOUNT", "LOAN", "MARGINAL_LENDING", "MONEY_MARKET", "MORTGAGE", "NON_RESIDENT_EXTERNAL", "OTHER", "OVERDRAFT", "OVERNIGHT_DEPOSIT", "PREPAID_CARD", "SALARY", "SAVINGS", "SETTLEMENT", "TAX", "UNKNOWN":
			return true
		}
	}
	return false
}
