// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

// AccountStatement - Statement information belonging to the account.
type AccountStatement struct {
	// Unique identifier for the statement.
	ID *string `json:"id,omitzero"`
	// Date and time of when the statement period starts.
	StartDateTime *time.Time `json:"startDateTime,omitzero"`
	// Date and time of when the statement period ends.
	EndDateTime *time.Time `json:"endDateTime,omitzero"`
	// Date and time of when the statement was created.
	CreationDateTime *time.Time `json:"creationDateTime,omitzero"`
}

func (a AccountStatement) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountStatement) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountStatement) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AccountStatement) GetStartDateTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.StartDateTime
}

func (a *AccountStatement) GetEndDateTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.EndDateTime
}

func (a *AccountStatement) GetCreationDateTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreationDateTime
}
