// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

// AccountRequest - __Conditional__. Used to further specify details of the `Consent` to request
//
// Conditions:
//
// 1. Mandatory to specify the individual scopes to request from the user at the `Institution` for an account authorisation
// 2. Mandatory to specify an expiry time on the created `Consent` at which time will render it unusable
// 3. Mandatory to specify the date range that the created `Consent` will be able to access transactions for (given the range is support for the `Institution`)
type AccountRequest struct {
	// __Optional__. Specifies the earliest date of the transaction records to be returned.
	//
	//  You must supply this field to retrieve transactions older than 90 days for banks accessed via the the [CBI Globe Gateway](/data/financial-data-resources/data-restrictions#cbi-globe-gateway).
	TransactionFrom *time.Time `json:"transactionFrom,omitzero"`
	// __Optional__. Specifies the latest date of the transaction records to be returned.
	TransactionTo *time.Time `json:"transactionTo,omitzero"`
	// __Optional__. Used to set a hard date for when the user's associated `Consent` will expire.
	//
	// **Note**: If this supported by the bank, specifying this is property is opting out of having a long-lived consent that can be perpetually re-authorised by the user. This will add an `expiresAt` field on the `Consent` object which will render it unusable after this date.
	//
	// **Note**: This is not supported by every `Institution`. In such case, the request will not fail but the property will be ignored and the created `Consent` will not have an expiry date.
	ExpiresAt *time.Time `json:"expiresAt,omitzero"`
	// __Conditional__. Used to create a request for the balance of the account specified. Once the user authorises the request, only the balance can be obtained by executing [GET Account Balances](./#get-account-balances).
	//
	//  This can be specified in conjunction with `accountIdentifiersForTransaction` to generate a `Consent` that can both access the accounts balance and transactions.
	AccountIdentifiers *AccountInfo `json:"accountIdentifiers,omitzero"`
	// __Conditional__. Used to create a request for the transactions of the account specified. Once the user authorises the request, only the transactions can be obtained by executing [GET Account Transactions](./#get-account-transactions).
	//
	// This can be specified in conjunction with `accountIdentifiersForBalance` to generate a `Consent` that can both access the accounts balance and transactions.
	AccountIdentifiersForTransaction []AccountInfo `json:"accountIdentifiersForTransaction,omitzero"`
	// __Conditional__. Used to create a request for the balance of the account specified. Once the user authorises the request, only the balance can be obtained by executing [GET Account Balances](./#get-account-balances).
	//
	//  This can be specified in conjunction with `accountIdentifiersForTransaction` to generate a `Consent` that can both access the accounts balance and transactions.
	AccountIdentifiersForBalance []AccountInfo `json:"accountIdentifiersForBalance,omitzero"`
	// __Optional__. Used to granularly specify the set of features that the user will give their consent for when requesting access to their account information. Depending on the `Institution`, this may also populate a consent screen which list these scopes before the user authorises.
	//
	// This endpoint accepts allow all [Financial Data Features](/guides/financial-data/features/#feature-list) that the `Institution` supports.To find out which scopes an `Institution` supports, check [GET Institution](./#get-institution).
	FeatureScope []FeatureEnum `json:"featureScope,omitzero"`
}

func (a AccountRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountRequest) GetTransactionFrom() *time.Time {
	if a == nil {
		return nil
	}
	return a.TransactionFrom
}

func (a *AccountRequest) GetTransactionTo() *time.Time {
	if a == nil {
		return nil
	}
	return a.TransactionTo
}

func (a *AccountRequest) GetExpiresAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.ExpiresAt
}

func (a *AccountRequest) GetAccountIdentifiers() *AccountInfo {
	if a == nil {
		return nil
	}
	return a.AccountIdentifiers
}

func (a *AccountRequest) GetAccountIdentifiersForTransaction() []AccountInfo {
	if a == nil {
		return nil
	}
	return a.AccountIdentifiersForTransaction
}

func (a *AccountRequest) GetAccountIdentifiersForBalance() []AccountInfo {
	if a == nil {
		return nil
	}
	return a.AccountIdentifiersForBalance
}

func (a *AccountRequest) GetFeatureScope() []FeatureEnum {
	if a == nil {
		return nil
	}
	return a.FeatureScope
}
