// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AlignmentEnum - __Mandatory__. Period alignment for which the payment limits are enforced. Allowed values are [CONSENT, CALENDAR]. If CONSENT, then period starts on consent creation date. If CALENDAR, then period lines up with the frequency e.g. WEEKLY period will begin at start of the week in question.
type AlignmentEnum string

const (
	AlignmentEnumConsent  AlignmentEnum = "CONSENT"
	AlignmentEnumCalendar AlignmentEnum = "CALENDAR"
)

func (e AlignmentEnum) ToPointer() *AlignmentEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AlignmentEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "CONSENT", "CALENDAR":
			return true
		}
	}
	return false
}
