// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AmountDetailsResponse - Monetary Amount.
type AmountDetailsResponse struct {
	// The monetary value
	Amount *float64 `json:"amount,omitzero"`
	// The [ISO 4217](https://www.xe.com/iso4217.php) currency code
	Currency *string `json:"currency,omitzero"`
}

func (a *AmountDetailsResponse) GetAmount() *float64 {
	if a == nil {
		return nil
	}
	return a.Amount
}

func (a *AmountDetailsResponse) GetCurrency() *string {
	if a == nil {
		return nil
	}
	return a.Currency
}
