// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Amount - __Mandatory__. Monetary Amount.
type Amount struct {
	// __Mandatory__. The monetary value
	Amount float64 `json:"amount"`
	// __Mandatory__. The [ISO 4217](https://www.xe.com/iso4217.php) currency code
	Currency string `json:"currency"`
}

func (a *Amount) GetAmount() float64 {
	if a == nil {
		return 0.0
	}
	return a.Amount
}

func (a *Amount) GetCurrency() string {
	if a == nil {
		return ""
	}
	return a.Currency
}
