// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// Issue - Detailed information regarding the issue that was experienced during processing of the request
type Issue struct {
	// Category of the issue
	Type *string `json:"type,omitzero"`
	// 5 digit Error Code that uniquely identifies the type of issue, for full list of error codes pelase check our documentation
	Code string `json:"code"`
	// Human readable description of the issue that was experienced
	Message string `json:"message"`
}

func (i *Issue) GetType() *string {
	if i == nil {
		return nil
	}
	return i.Type
}

func (i *Issue) GetCode() string {
	if i == nil {
		return ""
	}
	return i.Code
}

func (i *Issue) GetMessage() string {
	if i == nil {
		return ""
	}
	return i.Message
}

type Error struct {
	// Unique identifier of the request, used by Yapily for support purposes
	TracingID string `json:"tracingId"`
	// Numeric HTTP status code associated with the error
	Code int `json:"code"`
	// Textual description of the HTTP status
	Status string `json:"status"`
	// Link to where further information regarding the error can be found
	SupportURL *string `json:"supportUrl,omitzero"`
	// Source of the error. This may be YAPILY, the INSTITUTION, or the USER
	Source *string `json:"source,omitzero"`
	// List of issues relating to the error
	Issues []Issue `json:"issues"`
}

func (e *Error) GetTracingID() string {
	if e == nil {
		return ""
	}
	return e.TracingID
}

func (e *Error) GetCode() int {
	if e == nil {
		return 0
	}
	return e.Code
}

func (e *Error) GetStatus() string {
	if e == nil {
		return ""
	}
	return e.Status
}

func (e *Error) GetSupportURL() *string {
	if e == nil {
		return nil
	}
	return e.SupportURL
}

func (e *Error) GetSource() *string {
	if e == nil {
		return nil
	}
	return e.Source
}

func (e *Error) GetIssues() []Issue {
	if e == nil {
		return []Issue{}
	}
	return e.Issues
}

// APIErrorResponseV2 - API Error Response
type APIErrorResponseV2 struct {
	Error *Error `json:"error,omitzero"`
}

func (a APIErrorResponseV2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIErrorResponseV2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIErrorResponseV2) GetError() *Error {
	if a == nil {
		return nil
	}
	return a.Error
}

// #region class-body-apierrorresponsev2
// #endregion class-body-apierrorresponsev2
