// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// APIError - Provides details of the error that has occurred.
type APIError struct {
	// __Mandatory__. Numeric `HTTP` status code associated with the error.
	Code *int `json:"code,omitzero"`
	// Raw error details provided by the `Institution`, when it was the error source.
	InstitutionError *InstitutionError `json:"institutionError,omitzero"`
	// __Mandatory__. Description of the exact error that has been experienced.
	Message *string `json:"message,omitzero"`
	Source  *string `json:"source,omitzero"`
	// __Mandatory__. Textual description of the `HTTP` error status type.
	Status *string `json:"status,omitzero"`
	// __Optional__.  A unique identifier assigned by Yapily for the request that can be used for support purposes.
	TracingID *string `json:"tracingId,omitzero"`
}

func (a APIError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIError) GetCode() *int {
	if a == nil {
		return nil
	}
	return a.Code
}

func (a *APIError) GetInstitutionError() *InstitutionError {
	if a == nil {
		return nil
	}
	return a.InstitutionError
}

func (a *APIError) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

func (a *APIError) GetSource() *string {
	if a == nil {
		return nil
	}
	return a.Source
}

func (a *APIError) GetStatus() *string {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *APIError) GetTracingID() *string {
	if a == nil {
		return nil
	}
	return a.TracingID
}
