// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIListResponseOfDataConstraints struct {
	Meta *ResponseMeta             `json:"meta,omitzero"`
	Data []DataConstraintsResponse `json:"data,omitzero"`
}

func (a APIListResponseOfDataConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIListResponseOfDataConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIListResponseOfDataConstraints) GetMeta() *ResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIListResponseOfDataConstraints) GetData() []DataConstraintsResponse {
	if a == nil {
		return nil
	}
	return a.Data
}
