// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIListResponseOfDirectDebitResponse struct {
	Meta          *ResponseListMeta       `json:"meta,omitzero"`
	Data          []DirectDebitResponse   `json:"data,omitzero"`
	Links         map[string]string       `json:"links,omitzero"`
	ForwardedData []ResponseForwardedData `json:"forwardedData,omitzero"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Raw    []RawResponse                                 `json:"raw,omitzero"`
	Paging *FilteredClientPayloadListDirectDebitResponse `json:"paging,omitzero"`
}

func (a APIListResponseOfDirectDebitResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIListResponseOfDirectDebitResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIListResponseOfDirectDebitResponse) GetMeta() *ResponseListMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIListResponseOfDirectDebitResponse) GetData() []DirectDebitResponse {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *APIListResponseOfDirectDebitResponse) GetLinks() map[string]string {
	if a == nil {
		return nil
	}
	return a.Links
}

func (a *APIListResponseOfDirectDebitResponse) GetForwardedData() []ResponseForwardedData {
	if a == nil {
		return nil
	}
	return a.ForwardedData
}

func (a *APIListResponseOfDirectDebitResponse) GetRaw() []RawResponse {
	if a == nil {
		return nil
	}
	return a.Raw
}

func (a *APIListResponseOfDirectDebitResponse) GetPaging() *FilteredClientPayloadListDirectDebitResponse {
	if a == nil {
		return nil
	}
	return a.Paging
}
