// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIListResponseOfPaymentResponse struct {
	Meta          *ResponseListMeta       `json:"meta,omitzero"`
	Data          []PaymentResponse       `json:"data,omitzero"`
	Links         map[string]string       `json:"links,omitzero"`
	ForwardedData []ResponseForwardedData `json:"forwardedData,omitzero"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Raw    []RawResponse                             `json:"raw,omitzero"`
	Paging *FilteredClientPayloadListPaymentResponse `json:"paging,omitzero"`
}

func (a APIListResponseOfPaymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIListResponseOfPaymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIListResponseOfPaymentResponse) GetMeta() *ResponseListMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIListResponseOfPaymentResponse) GetData() []PaymentResponse {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *APIListResponseOfPaymentResponse) GetLinks() map[string]string {
	if a == nil {
		return nil
	}
	return a.Links
}

func (a *APIListResponseOfPaymentResponse) GetForwardedData() []ResponseForwardedData {
	if a == nil {
		return nil
	}
	return a.ForwardedData
}

func (a *APIListResponseOfPaymentResponse) GetRaw() []RawResponse {
	if a == nil {
		return nil
	}
	return a.Raw
}

func (a *APIListResponseOfPaymentResponse) GetPaging() *FilteredClientPayloadListPaymentResponse {
	if a == nil {
		return nil
	}
	return a.Paging
}
