// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIListResponseOfPaymentConstraints struct {
	Meta *ResponseListMeta            `json:"meta,omitzero"`
	Data []PaymentConstraintsResponse `json:"data,omitzero"`
}

func (a APIListResponseOfPaymentConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIListResponseOfPaymentConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIListResponseOfPaymentConstraints) GetMeta() *ResponseListMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIListResponseOfPaymentConstraints) GetData() []PaymentConstraintsResponse {
	if a == nil {
		return nil
	}
	return a.Data
}
