// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIResponseOfPaymentAuthorisationRequestResponse struct {
	Meta          *ResponseMeta                        `json:"meta,omitzero"`
	Data          *PaymentAuthorisationRequestResponse `json:"data,omitzero"`
	Links         map[string]string                    `json:"links,omitzero"`
	ForwardedData []ResponseForwardedData              `json:"forwardedData,omitzero"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Raw []RawResponse `json:"raw,omitzero"`
}

func (a APIResponseOfPaymentAuthorisationRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfPaymentAuthorisationRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfPaymentAuthorisationRequestResponse) GetMeta() *ResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIResponseOfPaymentAuthorisationRequestResponse) GetData() *PaymentAuthorisationRequestResponse {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *APIResponseOfPaymentAuthorisationRequestResponse) GetLinks() map[string]string {
	if a == nil {
		return nil
	}
	return a.Links
}

func (a *APIResponseOfPaymentAuthorisationRequestResponse) GetForwardedData() []ResponseForwardedData {
	if a == nil {
		return nil
	}
	return a.ForwardedData
}

func (a *APIResponseOfPaymentAuthorisationRequestResponse) GetRaw() []RawResponse {
	if a == nil {
		return nil
	}
	return a.Raw
}
