// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIResponseOfCreateHostedConsentRequest struct {
	Meta *ResponseMeta                 `json:"meta,omitzero"`
	Data *HostedConsentRequestResponse `json:"data,omitzero"`
}

func (a APIResponseOfCreateHostedConsentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfCreateHostedConsentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfCreateHostedConsentRequest) GetMeta() *ResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIResponseOfCreateHostedConsentRequest) GetData() *HostedConsentRequestResponse {
	if a == nil {
		return nil
	}
	return a.Data
}
