// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIResponseOfGetHostedConsentRequest struct {
	Meta *ResponseMeta                    `json:"meta,omitzero"`
	Data *HostedGetConsentRequestResponse `json:"data,omitzero"`
}

func (a APIResponseOfGetHostedConsentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfGetHostedConsentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfGetHostedConsentRequest) GetMeta() *ResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIResponseOfGetHostedConsentRequest) GetData() *HostedGetConsentRequestResponse {
	if a == nil {
		return nil
	}
	return a.Data
}
