// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIResponseOfIdentity struct {
	Meta *ResponseMeta `json:"meta,omitzero"`
	// Identification details of a party associated with an account e.g. (account owner or operator).
	Data          *Identity               `json:"data,omitzero"`
	Links         map[string]string       `json:"links,omitzero"`
	ForwardedData []ResponseForwardedData `json:"forwardedData,omitzero"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Raw []RawResponse `json:"raw,omitzero"`
}

func (a APIResponseOfIdentity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfIdentity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfIdentity) GetMeta() *ResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIResponseOfIdentity) GetData() *Identity {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *APIResponseOfIdentity) GetLinks() map[string]string {
	if a == nil {
		return nil
	}
	return a.Links
}

func (a *APIResponseOfIdentity) GetForwardedData() []ResponseForwardedData {
	if a == nil {
		return nil
	}
	return a.ForwardedData
}

func (a *APIResponseOfIdentity) GetRaw() []RawResponse {
	if a == nil {
		return nil
	}
	return a.Raw
}
