// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

type APIResponseOfGetCategorisedTransactionsRequestMeta struct {
	TracingID *string `json:"tracingId,omitzero"`
	// Total number of categorised transactions available
	Count *int64 `json:"count,omitzero"`
	// Total number of pages available, calculated based on the limit per page sent in the request.
	PageCount *int64 `json:"pageCount,omitzero"`
}

func (a *APIResponseOfGetCategorisedTransactionsRequestMeta) GetTracingID() *string {
	if a == nil {
		return nil
	}
	return a.TracingID
}

func (a *APIResponseOfGetCategorisedTransactionsRequestMeta) GetCount() *int64 {
	if a == nil {
		return nil
	}
	return a.Count
}

func (a *APIResponseOfGetCategorisedTransactionsRequestMeta) GetPageCount() *int64 {
	if a == nil {
		return nil
	}
	return a.PageCount
}

// APIResponseOfGetCategorisedTransactionsRequestTransactionHash - A unique identifier for the transaction that was generated by Yapily. It is a hash of some transaction attributes that is useful when no other identifier is present for instance.
type APIResponseOfGetCategorisedTransactionsRequestTransactionHash struct {
	Hash string `json:"hash"`
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransactionHash) GetHash() string {
	if a == nil {
		return ""
	}
	return a.Hash
}

// APIResponseOfGetCategorisedTransactionsRequestCategorisation - Categories associated with the transaction (see [categories list](/data/data-plus/categorisation-list))
type APIResponseOfGetCategorisedTransactionsRequestCategorisation struct {
	Categories []string `json:"categories"`
}

func (a *APIResponseOfGetCategorisedTransactionsRequestCategorisation) GetCategories() []string {
	if a == nil {
		return []string{}
	}
	return a.Categories
}

// APIResponseOfGetCategorisedTransactionsRequestEnrichmentMerchant - Processed merchant information
type APIResponseOfGetCategorisedTransactionsRequestEnrichmentMerchant struct {
	// The unique identifier for the merchant
	ID *string `json:"id,omitzero"`
	// The familiar name of the merchant (eg. 'Waitrose', 'Uber')
	Name *string `json:"name,omitzero"`
	// The logo of the merchant, formatted as a URL
	Logo *string `json:"logo,omitzero"`
}

func (a *APIResponseOfGetCategorisedTransactionsRequestEnrichmentMerchant) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *APIResponseOfGetCategorisedTransactionsRequestEnrichmentMerchant) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *APIResponseOfGetCategorisedTransactionsRequestEnrichmentMerchant) GetLogo() *string {
	if a == nil {
		return nil
	}
	return a.Logo
}

// APIResponseOfGetCategorisedTransactionsRequestEnrichment - Enrichment/Categorisation data
type APIResponseOfGetCategorisedTransactionsRequestEnrichment struct {
	// A unique identifier for the transaction that was generated by Yapily. It is a hash of some transaction attributes that is useful when no other identifier is present for instance.
	TransactionHash APIResponseOfGetCategorisedTransactionsRequestTransactionHash `json:"transactionHash"`
	// Categories associated with the transaction (see [categories list](/data/data-plus/categorisation-list))
	Categorisation APIResponseOfGetCategorisedTransactionsRequestCategorisation `json:"categorisation"`
	// Processed merchant information
	Merchant *APIResponseOfGetCategorisedTransactionsRequestEnrichmentMerchant `json:"merchant,omitzero"`
}

func (a APIResponseOfGetCategorisedTransactionsRequestEnrichment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfGetCategorisedTransactionsRequestEnrichment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfGetCategorisedTransactionsRequestEnrichment) GetTransactionHash() APIResponseOfGetCategorisedTransactionsRequestTransactionHash {
	if a == nil {
		return APIResponseOfGetCategorisedTransactionsRequestTransactionHash{}
	}
	return a.TransactionHash
}

func (a *APIResponseOfGetCategorisedTransactionsRequestEnrichment) GetCategorisation() APIResponseOfGetCategorisedTransactionsRequestCategorisation {
	if a == nil {
		return APIResponseOfGetCategorisedTransactionsRequestCategorisation{}
	}
	return a.Categorisation
}

func (a *APIResponseOfGetCategorisedTransactionsRequestEnrichment) GetMerchant() *APIResponseOfGetCategorisedTransactionsRequestEnrichmentMerchant {
	if a == nil {
		return nil
	}
	return a.Merchant
}

// APIResponseOfGetCategorisedTransactionsRequestMerchant - Generic merchant information
type APIResponseOfGetCategorisedTransactionsRequestMerchant struct {
	// An ISO 18245 code specifying the goods and services that the merchant provides (eg. `5411` for Grocery Stores and Supermarkets)
	MerchantCategoryCode *string `json:"merchantCategoryCode,omitzero"`
}

func (a *APIResponseOfGetCategorisedTransactionsRequestMerchant) GetMerchantCategoryCode() *string {
	if a == nil {
		return nil
	}
	return a.MerchantCategoryCode
}

// TransactionAmount - The amount associated with the transaction
type TransactionAmount struct {
	// The monetary amount (a positive value implies _incoming_ transaction and a negative value implies _outgoing_ transaction)
	Amount float64 `json:"amount"`
	// The [ISO 4217](https://www.xe.com/iso4217.php) currency code
	Currency string `json:"currency"`
}

func (t *TransactionAmount) GetAmount() float64 {
	if t == nil {
		return 0.0
	}
	return t.Amount
}

func (t *TransactionAmount) GetCurrency() string {
	if t == nil {
		return ""
	}
	return t.Currency
}

// APIResponseOfGetCategorisedTransactionsRequestProprietaryBankTransactionCode - __Conditional.__ A transaction code that is proprietary to the issuer institution
//
// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
type APIResponseOfGetCategorisedTransactionsRequestProprietaryBankTransactionCode struct {
	Code   *string `json:"code,omitzero"`
	Issuer *string `json:"issuer,omitzero"`
}

func (a *APIResponseOfGetCategorisedTransactionsRequestProprietaryBankTransactionCode) GetCode() *string {
	if a == nil {
		return nil
	}
	return a.Code
}

func (a *APIResponseOfGetCategorisedTransactionsRequestProprietaryBankTransactionCode) GetIssuer() *string {
	if a == nil {
		return nil
	}
	return a.Issuer
}

// DomainCode - The domain of the transaction
type DomainCode struct {
	// Unique identifier of the ISO code
	Code *string `json:"code,omitzero"`
	// Name of the ISO code
	Name *string `json:"name,omitzero"`
}

func (d *DomainCode) GetCode() *string {
	if d == nil {
		return nil
	}
	return d.Code
}

func (d *DomainCode) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

// FamilyCode - The family of the transaction
type FamilyCode struct {
	// Unique identifier of the ISO code
	Code *string `json:"code,omitzero"`
	// Name of the ISO code
	Name *string `json:"name,omitzero"`
}

func (f *FamilyCode) GetCode() *string {
	if f == nil {
		return nil
	}
	return f.Code
}

func (f *FamilyCode) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

// SubFamilyCode - The sub-family of the transaction
type SubFamilyCode struct {
	// Unique identifier of the ISO code
	Code *string `json:"code,omitzero"`
	// Name of the ISO code
	Name *string `json:"name,omitzero"`
}

func (s *SubFamilyCode) GetCode() *string {
	if s == nil {
		return nil
	}
	return s.Code
}

func (s *SubFamilyCode) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

// APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode - __Conditional.__ The ISO 20022 codes specifying the type of the transaction (eg. domain of 'Payments', family of 'Issued Credit Transfers', and sub-family of 'Domestic Credit Transfer')
//
// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
type APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode struct {
	// The domain of the transaction
	DomainCode *DomainCode `json:"domainCode,omitzero"`
	// The family of the transaction
	FamilyCode *FamilyCode `json:"familyCode,omitzero"`
	// The sub-family of the transaction
	SubFamilyCode *SubFamilyCode `json:"subFamilyCode,omitzero"`
}

func (a APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode) GetDomainCode() *DomainCode {
	if a == nil {
		return nil
	}
	return a.DomainCode
}

func (a *APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode) GetFamilyCode() *FamilyCode {
	if a == nil {
		return nil
	}
	return a.FamilyCode
}

func (a *APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode) GetSubFamilyCode() *SubFamilyCode {
	if a == nil {
		return nil
	}
	return a.SubFamilyCode
}

type BalanceAmount struct {
	Amount   *int64  `json:"amount,omitzero"`
	Currency *string `json:"currency,omitzero"`
}

func (b *BalanceAmount) GetAmount() *int64 {
	if b == nil {
		return nil
	}
	return b.Amount
}

func (b *BalanceAmount) GetCurrency() *string {
	if b == nil {
		return nil
	}
	return b.Currency
}

// Balance - __Conditional.__ The account balance around the time of the transaction (the exact timing is dictated by the balance type)
//
// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
type Balance struct {
	// Enum: `CLOSING_AVAILABLE`, `CLOSING_BOOKED`, `CLOSING_CLEARED`, `EXPECTED`, `FORWARD_AVAILABLE`, `INFORMATION`, `INTERIM_AVAILABLE`, `INTERIM_BOOKED`, `INTERIM_CLEARED`, `OPENING_AVAILABLE`, `OPENING_BOOKED`, `OPENING_CLEARED`, `PREVIOUSLY_CLOSED_BOOKED`, `AUTHORISED`, `OTHER`, `UNKNOWN`
	Type          *string        `json:"type,omitzero"`
	BalanceAmount *BalanceAmount `json:"balanceAmount,omitzero"`
}

func (b Balance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Balance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *Balance) GetType() *string {
	if b == nil {
		return nil
	}
	return b.Type
}

func (b *Balance) GetBalanceAmount() *BalanceAmount {
	if b == nil {
		return nil
	}
	return b.BalanceAmount
}

type APIResponseOfGetCategorisedTransactionsRequestTransaction struct {
	// Enrichment/Categorisation data
	Enrichment APIResponseOfGetCategorisedTransactionsRequestEnrichment `json:"enrichment"`
	// Processed type of recurrence for the transaction (eg. 'one off', 'subscription')
	Recurrence *string `json:"recurrence,omitzero"`
	// Processed payment provider for the transaction (eg. 'PayPal')
	PaymentProcessor *string `json:"paymentProcessor,omitzero"`
	// Processed location of the transaction/merchant derived from the transaction's description, formatted as an address
	Location *string `json:"location,omitzero"`
	// Generic merchant information
	Merchant *APIResponseOfGetCategorisedTransactionsRequestMerchant `json:"merchant,omitzero"`
	// __Conditional.__ An identifier for the transaction retrieved from Yapily AIS (ie. present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation))
	ID *string `json:"id,omitzero"`
	// The date and time when the transaction happened
	Date time.Time `json:"date"`
	// The description associated with the transaction
	Description string `json:"description"`
	// The amount associated with the transaction
	TransactionAmount TransactionAmount `json:"transactionAmount"`
	// __Conditional.__ The date and time when the transaction was booked
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	BookingDateTime *time.Time `json:"bookingDateTime,omitzero"`
	// __Conditional.__ The date and time when the funds either cease to be available (for _outgoing_ transactions) or become available to the account owner (for _incoming_ transactions)
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	ValueDateTime *time.Time `json:"valueDateTime,omitzero"`
	// __Conditional.__ The status of the transaction. Enum: `BOOKED`, `PENDING`
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	Status *string `json:"status,omitzero"`
	// __Conditional.__ The monetary amount (a positive value implies _incoming_ transaction and a negative value implies _outgoing_ transaction)
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	Amount *float64 `json:"amount,omitzero"`
	// __Conditional.__ The [ISO 4217](https://www.xe.com/iso4217.php) currency code
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	Currency *string `json:"currency,omitzero"`
	// __Conditional.__ The reference associated with the transaction
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	Reference *string `json:"reference,omitzero"`
	// __Conditional.__ Other details associated with the transaction. This is narrative data, caught as unstructured text.
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	TransactionInformation []string `json:"transactionInformation,omitzero"`
	// __Conditional.__ A transaction code that is proprietary to the issuer institution
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	ProprietaryBankTransactionCode *APIResponseOfGetCategorisedTransactionsRequestProprietaryBankTransactionCode `json:"proprietaryBankTransactionCode,omitzero"`
	// __Conditional.__ The ISO 20022 codes specifying the type of the transaction (eg. domain of 'Payments', family of 'Issued Credit Transfers', and sub-family of 'Domestic Credit Transfer')
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	IsoBankTransactionCode *APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode `json:"isoBankTransactionCode,omitzero"`
	// __Conditional.__ The account balance around the time of the transaction (the exact timing is dictated by the balance type)
	//
	// This may be present when using [Transactions and Categorisation endpoint](/api-reference/post-accounts-accountId-transactions-categorisation)
	Balance *Balance `json:"balance,omitzero"`
}

func (a APIResponseOfGetCategorisedTransactionsRequestTransaction) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetEnrichment() APIResponseOfGetCategorisedTransactionsRequestEnrichment {
	if a == nil {
		return APIResponseOfGetCategorisedTransactionsRequestEnrichment{}
	}
	return a.Enrichment
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetRecurrence() *string {
	if a == nil {
		return nil
	}
	return a.Recurrence
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetPaymentProcessor() *string {
	if a == nil {
		return nil
	}
	return a.PaymentProcessor
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetLocation() *string {
	if a == nil {
		return nil
	}
	return a.Location
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetMerchant() *APIResponseOfGetCategorisedTransactionsRequestMerchant {
	if a == nil {
		return nil
	}
	return a.Merchant
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetDate() time.Time {
	if a == nil {
		return time.Time{}
	}
	return a.Date
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetDescription() string {
	if a == nil {
		return ""
	}
	return a.Description
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetTransactionAmount() TransactionAmount {
	if a == nil {
		return TransactionAmount{}
	}
	return a.TransactionAmount
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetBookingDateTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.BookingDateTime
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetValueDateTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.ValueDateTime
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetStatus() *string {
	if a == nil {
		return nil
	}
	return a.Status
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetAmount() *float64 {
	if a == nil {
		return nil
	}
	return a.Amount
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetCurrency() *string {
	if a == nil {
		return nil
	}
	return a.Currency
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetReference() *string {
	if a == nil {
		return nil
	}
	return a.Reference
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetTransactionInformation() []string {
	if a == nil {
		return nil
	}
	return a.TransactionInformation
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetProprietaryBankTransactionCode() *APIResponseOfGetCategorisedTransactionsRequestProprietaryBankTransactionCode {
	if a == nil {
		return nil
	}
	return a.ProprietaryBankTransactionCode
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetIsoBankTransactionCode() *APIResponseOfGetCategorisedTransactionsRequestIsoBankTransactionCode {
	if a == nil {
		return nil
	}
	return a.IsoBankTransactionCode
}

func (a *APIResponseOfGetCategorisedTransactionsRequestTransaction) GetBalance() *Balance {
	if a == nil {
		return nil
	}
	return a.Balance
}

type APIResponseOfGetCategorisedTransactionsRequestData struct {
	Transactions []APIResponseOfGetCategorisedTransactionsRequestTransaction `json:"transactions"`
}

func (a *APIResponseOfGetCategorisedTransactionsRequestData) GetTransactions() []APIResponseOfGetCategorisedTransactionsRequestTransaction {
	if a == nil {
		return []APIResponseOfGetCategorisedTransactionsRequestTransaction{}
	}
	return a.Transactions
}

type APIResponseOfGetCategorisedTransactionsRequestLinks struct {
	First *string `json:"first,omitzero"`
	Prev  *string `json:"prev,omitzero"`
	Self  *string `json:"self,omitzero"`
	Next  *string `json:"next,omitzero"`
	Last  *string `json:"last,omitzero"`
}

func (a *APIResponseOfGetCategorisedTransactionsRequestLinks) GetFirst() *string {
	if a == nil {
		return nil
	}
	return a.First
}

func (a *APIResponseOfGetCategorisedTransactionsRequestLinks) GetPrev() *string {
	if a == nil {
		return nil
	}
	return a.Prev
}

func (a *APIResponseOfGetCategorisedTransactionsRequestLinks) GetSelf() *string {
	if a == nil {
		return nil
	}
	return a.Self
}

func (a *APIResponseOfGetCategorisedTransactionsRequestLinks) GetNext() *string {
	if a == nil {
		return nil
	}
	return a.Next
}

func (a *APIResponseOfGetCategorisedTransactionsRequestLinks) GetLast() *string {
	if a == nil {
		return nil
	}
	return a.Last
}

type APIResponseOfGetCategorisedTransactionsRequest struct {
	Meta  *APIResponseOfGetCategorisedTransactionsRequestMeta  `json:"meta,omitzero"`
	Data  *APIResponseOfGetCategorisedTransactionsRequestData  `json:"data,omitzero"`
	Links *APIResponseOfGetCategorisedTransactionsRequestLinks `json:"links,omitzero"`
}

func (a APIResponseOfGetCategorisedTransactionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfGetCategorisedTransactionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfGetCategorisedTransactionsRequest) GetMeta() *APIResponseOfGetCategorisedTransactionsRequestMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIResponseOfGetCategorisedTransactionsRequest) GetData() *APIResponseOfGetCategorisedTransactionsRequestData {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *APIResponseOfGetCategorisedTransactionsRequest) GetLinks() *APIResponseOfGetCategorisedTransactionsRequestLinks {
	if a == nil {
		return nil
	}
	return a.Links
}
