// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIResponseOfCreateTransactionsCategorisationRequestMeta struct {
	TracingID *string `json:"tracingId,omitzero"`
}

func (a *APIResponseOfCreateTransactionsCategorisationRequestMeta) GetTracingID() *string {
	if a == nil {
		return nil
	}
	return a.TracingID
}

type APIResponseOfCreateTransactionsCategorisationRequestData struct {
	CategorisationID *string `json:"categorisationId,omitzero"`
}

func (a *APIResponseOfCreateTransactionsCategorisationRequestData) GetCategorisationID() *string {
	if a == nil {
		return nil
	}
	return a.CategorisationID
}

type APIResponseOfCreateTransactionsCategorisationRequest struct {
	Meta *APIResponseOfCreateTransactionsCategorisationRequestMeta `json:"meta,omitzero"`
	Data *APIResponseOfCreateTransactionsCategorisationRequestData `json:"data,omitzero"`
}

func (a APIResponseOfCreateTransactionsCategorisationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfCreateTransactionsCategorisationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfCreateTransactionsCategorisationRequest) GetMeta() *APIResponseOfCreateTransactionsCategorisationRequestMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIResponseOfCreateTransactionsCategorisationRequest) GetData() *APIResponseOfCreateTransactionsCategorisationRequestData {
	if a == nil {
		return nil
	}
	return a.Data
}
