// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIResponseOfVrpSubmissionResponse struct {
	Meta          *ResponseMeta           `json:"meta,omitzero"`
	Data          *VrpSubmissionResponse  `json:"data,omitzero"`
	Links         map[string]string       `json:"links,omitzero"`
	ForwardedData []ResponseForwardedData `json:"forwardedData,omitzero"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Raw []RawResponse `json:"raw,omitzero"`
}

func (a APIResponseOfVrpSubmissionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfVrpSubmissionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfVrpSubmissionResponse) GetMeta() *ResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIResponseOfVrpSubmissionResponse) GetData() *VrpSubmissionResponse {
	if a == nil {
		return nil
	}
	return a.Data
}

func (a *APIResponseOfVrpSubmissionResponse) GetLinks() map[string]string {
	if a == nil {
		return nil
	}
	return a.Links
}

func (a *APIResponseOfVrpSubmissionResponse) GetForwardedData() []ResponseForwardedData {
	if a == nil {
		return nil
	}
	return a.ForwardedData
}

func (a *APIResponseOfVrpSubmissionResponse) GetRaw() []RawResponse {
	if a == nil {
		return nil
	}
	return a.Raw
}
