// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type APIResponseOfGetHostedPaymentRequest struct {
	Meta *ResponseMeta         `json:"meta,omitzero"`
	Data *HostedPaymentDetails `json:"data,omitzero"`
}

func (a APIResponseOfGetHostedPaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *APIResponseOfGetHostedPaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *APIResponseOfGetHostedPaymentRequest) GetMeta() *ResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *APIResponseOfGetHostedPaymentRequest) GetData() *HostedPaymentDetails {
	if a == nil {
		return nil
	}
	return a.Data
}
