// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

// ApplicationUser - Information about a user of an application.
type ApplicationUser struct {
	// A unique identifier for the 'User' assigned by Yapily.
	UUID *string `json:"uuid,omitzero"`
	// Unique identifier of the application the user is associated with.
	ApplicationUUID *string `json:"applicationUuid,omitzero"`
	// __Conditional__. The user-friendly reference to the `User`.
	ApplicationUserID *string `json:"applicationUserId,omitzero"`
	ReferenceID       *string `json:"referenceId,omitzero"`
	// Date and time of when the user was created.
	CreatedAt           *time.Time           `json:"createdAt,omitzero"`
	InstitutionConsents []InstitutionConsent `json:"institutionConsents,omitzero"`
	// __Optional__. A flag to indicate whether the user has opted out of VOP.
	VopOptOut *bool `default:"false" json:"vopOptOut"`
}

func (a ApplicationUser) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplicationUser) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ApplicationUser) GetUUID() *string {
	if a == nil {
		return nil
	}
	return a.UUID
}

func (a *ApplicationUser) GetApplicationUUID() *string {
	if a == nil {
		return nil
	}
	return a.ApplicationUUID
}

func (a *ApplicationUser) GetApplicationUserID() *string {
	if a == nil {
		return nil
	}
	return a.ApplicationUserID
}

func (a *ApplicationUser) GetReferenceID() *string {
	if a == nil {
		return nil
	}
	return a.ReferenceID
}

func (a *ApplicationUser) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *ApplicationUser) GetInstitutionConsents() []InstitutionConsent {
	if a == nil {
		return nil
	}
	return a.InstitutionConsents
}

func (a *ApplicationUser) GetVopOptOut() *bool {
	if a == nil {
		return nil
	}
	return a.VopOptOut
}
