// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// ApplicationBeneficiaryResponse - Application beneficiary response.
type ApplicationBeneficiaryResponse struct {
	Meta *ResponseMeta `json:"meta,omitzero"`
	// Application beneficiary data response.
	Data *ApplicationBeneficiaryData `json:"data,omitzero"`
}

func (a ApplicationBeneficiaryResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ApplicationBeneficiaryResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ApplicationBeneficiaryResponse) GetMeta() *ResponseMeta {
	if a == nil {
		return nil
	}
	return a.Meta
}

func (a *ApplicationBeneficiaryResponse) GetData() *ApplicationBeneficiaryData {
	if a == nil {
		return nil
	}
	return a.Data
}
