// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuthorisationStatus - Current status of the embedded authorisation request in code form.
type AuthorisationStatus string

const (
	AuthorisationStatusAwaitingAuthorization             AuthorisationStatus = "AWAITING_AUTHORIZATION"
	AuthorisationStatusAwaitingFurtherAuthorization      AuthorisationStatus = "AWAITING_FURTHER_AUTHORIZATION"
	AuthorisationStatusAwaitingReAuthorization           AuthorisationStatus = "AWAITING_RE_AUTHORIZATION"
	AuthorisationStatusAuthorized                        AuthorisationStatus = "AUTHORIZED"
	AuthorisationStatusConsumed                          AuthorisationStatus = "CONSUMED"
	AuthorisationStatusRejected                          AuthorisationStatus = "REJECTED"
	AuthorisationStatusRevoked                           AuthorisationStatus = "REVOKED"
	AuthorisationStatusFailed                            AuthorisationStatus = "FAILED"
	AuthorisationStatusExpired                           AuthorisationStatus = "EXPIRED"
	AuthorisationStatusUnknown                           AuthorisationStatus = "UNKNOWN"
	AuthorisationStatusInvalid                           AuthorisationStatus = "INVALID"
	AuthorisationStatusAwaitingDecoupledPreAuthorization AuthorisationStatus = "AWAITING_DECOUPLED_PRE_AUTHORIZATION"
	AuthorisationStatusAwaitingPreAuthorization          AuthorisationStatus = "AWAITING_PRE_AUTHORIZATION"
	AuthorisationStatusPreAuthorized                     AuthorisationStatus = "PRE_AUTHORIZED"
	AuthorisationStatusAwaitingDecoupledAuthorization    AuthorisationStatus = "AWAITING_DECOUPLED_AUTHORIZATION"
	AuthorisationStatusAwaitingScaMethod                 AuthorisationStatus = "AWAITING_SCA_METHOD"
	AuthorisationStatusAwaitingScaCode                   AuthorisationStatus = "AWAITING_SCA_CODE"
)

func (e AuthorisationStatus) ToPointer() *AuthorisationStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AuthorisationStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "AWAITING_AUTHORIZATION", "AWAITING_FURTHER_AUTHORIZATION", "AWAITING_RE_AUTHORIZATION", "AUTHORIZED", "CONSUMED", "REJECTED", "REVOKED", "FAILED", "EXPIRED", "UNKNOWN", "INVALID", "AWAITING_DECOUPLED_PRE_AUTHORIZATION", "AWAITING_PRE_AUTHORIZATION", "PRE_AUTHORIZED", "AWAITING_DECOUPLED_AUTHORIZATION", "AWAITING_SCA_METHOD", "AWAITING_SCA_CODE":
			return true
		}
	}
	return false
}
