// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// BeneficiaryPayee - __Mandatory__. Account details belonging to the `Beneficiary Payee` (person/ business). You must define this in your payment request along with all of the nested mandatory properties.
type BeneficiaryPayee struct {
	// The account holder name of the beneficiary.
	Name *string `json:"name,omitzero"`
	// __Mandatory__. The account identifications that identify the `BeneficiaryPayee` bank account.
	AccountIdentifications []AccountIdentification `json:"accountIdentifications"`
	// __Conditional__. The address of the `Payee` or `Payer`.
	//
	// - `payee.address` is mandatory when the `paymentType` is an `INTERNATIONAL` payment
	// - An `Institution` may require you to specify the `country` when used in the context of the `Payee` to be able to make a payment.
	Address *Address `json:"address,omitzero"`
}

func (b BeneficiaryPayee) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BeneficiaryPayee) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BeneficiaryPayee) GetName() *string {
	if b == nil {
		return nil
	}
	return b.Name
}

func (b *BeneficiaryPayee) GetAccountIdentifications() []AccountIdentification {
	if b == nil {
		return []AccountIdentification{}
	}
	return b.AccountIdentifications
}

func (b *BeneficiaryPayee) GetAddress() *Address {
	if b == nil {
		return nil
	}
	return b.Address
}
