// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BeneficiaryMatchStatus string

const (
	BeneficiaryMatchStatusFullMatch                    BeneficiaryMatchStatus = "FULL_MATCH"
	BeneficiaryMatchStatusCloseMatch                   BeneficiaryMatchStatus = "CLOSE_MATCH"
	BeneficiaryMatchStatusNoMatch                      BeneficiaryMatchStatus = "NO_MATCH"
	BeneficiaryMatchStatusExempted                     BeneficiaryMatchStatus = "EXEMPTED"
	BeneficiaryMatchStatusVerificationCheckNotPossible BeneficiaryMatchStatus = "VERIFICATION_CHECK_NOT_POSSIBLE"
)

func (e BeneficiaryMatchStatus) ToPointer() *BeneficiaryMatchStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *BeneficiaryMatchStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "FULL_MATCH", "CLOSE_MATCH", "NO_MATCH", "EXEMPTED", "VERIFICATION_CHECK_NOT_POSSIBLE":
			return true
		}
	}
	return false
}
