// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

// BulkPaymentRequest - The payment request object defining the details of the bulk payment
type BulkPaymentRequest struct {
	// __Mandatory__. The array of `PaymentRequest` objects to initiate in the bulk payment.
	Payments []PaymentRequest `json:"payments"`
	// __Conditional__. The identification number of the originator.
	//
	// - Mandatory for AIB bulk payments
	// - Mandatory for HSBC Corporate bulk payments. This will be the Connect Profile ID
	OriginatorIdentificationNumber *string `json:"originatorIdentificationNumber,omitzero"`
	// __Optional__. Used to schedule the bulk payment to be executed at a future date if supported by the `Institution`. This value establishes the requirement for the subsequent payment submission. The final payment request must occur on the same calendar day as this timestamp to pass validation.
	ExecutionDateTime *time.Time `json:"executionDateTime,omitzero"`
}

func (b BulkPaymentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkPaymentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkPaymentRequest) GetPayments() []PaymentRequest {
	if b == nil {
		return []PaymentRequest{}
	}
	return b.Payments
}

func (b *BulkPaymentRequest) GetOriginatorIdentificationNumber() *string {
	if b == nil {
		return nil
	}
	return b.OriginatorIdentificationNumber
}

func (b *BulkPaymentRequest) GetExecutionDateTime() *time.Time {
	if b == nil {
		return nil
	}
	return b.ExecutionDateTime
}
