// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// BulkPaymentEmbeddedAuthorisationRequest - The request body containing a `BulkPaymentEmbeddedAuthorisationRequest` json payload
type BulkPaymentEmbeddedAuthorisationRequest struct {
	// __Conditional__. The reference to the `User` that will authorise the authorisation request using the Yapily generated UUID. Either the `userUuid` or `applicationUserId` must be provided.
	UserUUID *string `json:"userUuid,omitzero"`
	// __Conditional__. The user-friendly reference to the `User` that will authorise the authorisation request. If a `User` with the specified `applicationUserId` exists, it will be used otherwise, a new `User` with the specified `applicationUserId` will be created and used. Either the `userUuid` or `applicationUserId` must be provided.
	ApplicationUserID *string `json:"applicationUserId,omitzero"`
	// __Mandatory__. The reference to the `Institution` which identifies which institution the authorisation request is sent to.
	InstitutionID string `json:"institutionId"`
	// __Optional__. The server to redirect the user to after the user complete the authorisation at the `Institution`.
	//
	// See [Using a callback (Optional)](/open-banking-flow/handling-redirects/callback-url) for more information.
	Callback *string `json:"callback,omitzero"`
	// __Optional__. The server to redirect the user to after the user complete the authorisation at the `Institution`.
	Redirect *RedirectRequest `json:"redirect,omitzero"`
	// __Conditional__. Used to receive a `oneTimeToken` rather than a `consentToken` at the `callback` for additional security. This can only be used when the `callback` is set.
	//
	// See [Using a callback with an OTT (Optional)](/open-banking-flow/handling-redirects/callback-url) for more information.
	OneTimeToken *bool `json:"oneTimeToken,omitzero"`
	// The payment request object defining the details of the bulk payment
	PaymentRequest *BulkPaymentRequest `json:"paymentRequest,omitzero"`
	// __Conditional__. Used to capture the user's credentials to allow them to login to an `Institution` that uses the embedded account authorisation flow.
	//
	// This is the first step required in the embedded account authorisation flow to authorise the `Consent`.
	UserCredentials *UserCredentials `json:"userCredentials,omitzero"`
	// __Conditional__. Used to update the authorisation with the sca method of the user's choice for the `Institution` that uses the embedded authorisation flow. If the user has multiple sca methods configured, the `Institution` will allow the user to select from each of these options.
	//
	// When the user has multiple sca methods for the `Institution`, this is the second step required in the embedded authorisation flow to authorise the `Consent`.
	SelectedScaMethod *ScaMethod `json:"selectedScaMethod,omitzero"`
	// __Conditional__. Used to update the authorisation with the sca code received by the user from the `Institution` using the embedded payment authorisation flow.
	//
	// This is the penultimate step required in the embedded payment authorisation flow to authorise the `Consent`. After sending the sca code, to obtain an authorised consent, the last step is to poll [Get Consent](/api-reference/getConsentById) until the `Institution` authorises the request and the `Consent` `status` transitions to `AUTHORIZED`.
	ScaCode *string `json:"scaCode,omitzero"`
}

func (b BulkPaymentEmbeddedAuthorisationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetUserUUID() *string {
	if b == nil {
		return nil
	}
	return b.UserUUID
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetApplicationUserID() *string {
	if b == nil {
		return nil
	}
	return b.ApplicationUserID
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetInstitutionID() string {
	if b == nil {
		return ""
	}
	return b.InstitutionID
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetCallback() *string {
	if b == nil {
		return nil
	}
	return b.Callback
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetRedirect() *RedirectRequest {
	if b == nil {
		return nil
	}
	return b.Redirect
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetOneTimeToken() *bool {
	if b == nil {
		return nil
	}
	return b.OneTimeToken
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetPaymentRequest() *BulkPaymentRequest {
	if b == nil {
		return nil
	}
	return b.PaymentRequest
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetUserCredentials() *UserCredentials {
	if b == nil {
		return nil
	}
	return b.UserCredentials
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetSelectedScaMethod() *ScaMethod {
	if b == nil {
		return nil
	}
	return b.SelectedScaMethod
}

func (b *BulkPaymentEmbeddedAuthorisationRequest) GetScaCode() *string {
	if b == nil {
		return nil
	}
	return b.ScaCode
}
