// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ChargeBearerType - __Conditional__. Depending on the bank and payment type for international Euro payments. The field ChargeBearer specifies which party/parties will bear the charges associated with the processing of the payment transaction. Valid values are:
//
// - `DEBT` - All transaction charges are to be borne by the debtor.
// - `CRED` - All transaction charges are to be borne by the creditor.
// - `SHAR` - In a credit transfer context, means that transaction charges on the sender side are to be borne by the debtor, transaction charges on the receiver side are to be borne by the creditor
// - `SLEV` - Charges are to be applied following the rules agreed in the service level and/or scheme.
type ChargeBearerType string

const (
	ChargeBearerTypeDebt ChargeBearerType = "DEBT"
	ChargeBearerTypeCred ChargeBearerType = "CRED"
	ChargeBearerTypeShar ChargeBearerType = "SHAR"
	ChargeBearerTypeSlev ChargeBearerType = "SLEV"
)

func (e ChargeBearerType) ToPointer() *ChargeBearerType {
	return &e
}
func (e *ChargeBearerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DEBT":
		fallthrough
	case "CRED":
		fallthrough
	case "SHAR":
		fallthrough
	case "SLEV":
		*e = ChargeBearerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChargeBearerType: %v", v)
	}
}
