// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ConsentAuthCodeRequest - The request body containing the `ConsentAuthCodeRequest` json payload
type ConsentAuthCodeRequest struct {
	// __Mandatory__. The authorisation code
	AuthCode string `json:"authCode"`
	// __Mandatory__. The authorisation state
	AuthState string `json:"authState"`
}

func (c *ConsentAuthCodeRequest) GetAuthCode() string {
	if c == nil {
		return ""
	}
	return c.AuthCode
}

func (c *ConsentAuthCodeRequest) GetAuthState() string {
	if c == nil {
		return ""
	}
	return c.AuthState
}
