// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// ConsolidatedAccountInformation - Summary information regarding account balances of the overall account provided by the bank
type ConsolidatedAccountInformation struct {
	// Identifier of the consolidated account. When used in Get Account Transactions calls, the transactions between the sub-accounts will not be reported
	ID              *string          `json:"id,omitzero"`
	AccountBalances []AccountBalance `json:"accountBalances,omitzero"`
}

func (c ConsolidatedAccountInformation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConsolidatedAccountInformation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConsolidatedAccountInformation) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ConsolidatedAccountInformation) GetAccountBalances() []AccountBalance {
	if c == nil {
		return nil
	}
	return c.AccountBalances
}
