// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

type ConsentDeleteResponse struct {
	// __Conditional__. User-friendly identifier of the `User` that provides authorisation. If a `User` with the specified `applicationUserId` exists, it will be used otherwise, a new `User` with the specified `applicationUserId` will be created and used. Either the `userUuid` or `applicationUserId` must be provided.
	ID *string `json:"id,omitzero"`
	// Indicates the outcome of the delete request.
	DeleteStatus *DeleteStatusEnum `json:"deleteStatus,omitzero"`
	// __Mandatory__. The `Institution` the authorisation request is sent to.
	InstitutionID *string `json:"institutionId,omitzero"`
	// Identification of the consent at the Institution.
	InstitutionConsentID *string `json:"institutionConsentId,omitzero"`
	// Date and time of when the consent was authorised.
	CreationDate *time.Time `json:"creationDate,omitzero"`
}

func (c ConsentDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConsentDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConsentDeleteResponse) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *ConsentDeleteResponse) GetDeleteStatus() *DeleteStatusEnum {
	if c == nil {
		return nil
	}
	return c.DeleteStatus
}

func (c *ConsentDeleteResponse) GetInstitutionID() *string {
	if c == nil {
		return nil
	}
	return c.InstitutionID
}

func (c *ConsentDeleteResponse) GetInstitutionConsentID() *string {
	if c == nil {
		return nil
	}
	return c.InstitutionConsentID
}

func (c *ConsentDeleteResponse) GetCreationDate() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreationDate
}
