// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type CreateHostedConsentRequest struct {
	// __Conditional__. Yapily Identifier for the `User` returned by the create user step POST /users. You must provide either a `userId` or `applicationUserId`.
	UserID *string `json:"userId,omitzero"`
	// __Conditional__. Your own `User` reference. This field allows you to use your own unique references for individual users. Where the `User` reference doesn't have an associated Yapily `userId`, a new `userId` is created and linked to it. You must provide either a `userId` or `applicationUserId`.
	ApplicationUserID *string `json:"applicationUserId,omitzero"`
	// Specifies the institution requirements for making the payment. Skips the bank selection screen in payment flow if the `institutionId` and `institutionCountryCode` are provided.
	InstitutionIdentifiers InstitutionIdentifiers `json:"institutionIdentifiers"`
	// Specifies the language and location preferences of the user.
	UserSettings *UserSettings `json:"userSettings,omitzero"`
	// URL of your server to redirect the user after completion of the consent flow.
	RedirectURL string `json:"redirectUrl"`
	// Used to receive a oneTimeToken rather than a consentToken at the redirectUrl for additional security.
	OneTimeToken *bool `json:"oneTimeToken,omitzero"`
	// __Conditional__. Used to further specify details of the `Consent` to request
	//
	// Conditions:
	//
	// 1. Mandatory to specify the individual scopes to request from the user at the `Institution` for an account authorisation
	// 2. Mandatory to specify an expiry time on the created `Consent` at which time will render it unusable
	// 3. Mandatory to specify the date range that the created `Consent` will be able to access transactions for (given the range is support for the `Institution`)
	AccountRequest *HostedAccountRequest `json:"accountRequest,omitzero"`
}

func (c CreateHostedConsentRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateHostedConsentRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateHostedConsentRequest) GetUserID() *string {
	if c == nil {
		return nil
	}
	return c.UserID
}

func (c *CreateHostedConsentRequest) GetApplicationUserID() *string {
	if c == nil {
		return nil
	}
	return c.ApplicationUserID
}

func (c *CreateHostedConsentRequest) GetInstitutionIdentifiers() InstitutionIdentifiers {
	if c == nil {
		return InstitutionIdentifiers{}
	}
	return c.InstitutionIdentifiers
}

func (c *CreateHostedConsentRequest) GetUserSettings() *UserSettings {
	if c == nil {
		return nil
	}
	return c.UserSettings
}

func (c *CreateHostedConsentRequest) GetRedirectURL() string {
	if c == nil {
		return ""
	}
	return c.RedirectURL
}

func (c *CreateHostedConsentRequest) GetOneTimeToken() *bool {
	if c == nil {
		return nil
	}
	return c.OneTimeToken
}

func (c *CreateHostedConsentRequest) GetAccountRequest() *HostedAccountRequest {
	if c == nil {
		return nil
	}
	return c.AccountRequest
}
