// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CreditLineType - __Mandatory__. The type of credit that has been provided.
type CreditLineType string

const (
	CreditLineTypeAvailable CreditLineType = "AVAILABLE"
	CreditLineTypeCredit    CreditLineType = "CREDIT"
	CreditLineTypeEmergency CreditLineType = "EMERGENCY"
	CreditLineTypePreAgreed CreditLineType = "PRE_AGREED"
	CreditLineTypeTemporary CreditLineType = "TEMPORARY"
	CreditLineTypeOther     CreditLineType = "OTHER"
	CreditLineTypeUnknown   CreditLineType = "UNKNOWN"
)

func (e CreditLineType) ToPointer() *CreditLineType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *CreditLineType) IsExact() bool {
	if e != nil {
		switch *e {
		case "AVAILABLE", "CREDIT", "EMERGENCY", "PRE_AGREED", "TEMPORARY", "OTHER", "UNKNOWN":
			return true
		}
	}
	return false
}
