// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type DataConstraintsResponse struct {
	// The id to represent the `Institution`.
	InstitutionID string `json:"institutionId"`
	// 2 letter ISO Country code of the `Institution`.
	InstitutionCountryCode *string `json:"institutionCountryCode,omitzero"`
	// Define the applicable API end point.
	EndpointPath *string `json:"endpointPath,omitzero"`
	// Https Method for the endpoint.
	EndpointMethod *string `json:"endpointMethod,omitzero"`
	// Object defining the constraints rules applicable for a given requests.
	Request RequestConstraints `json:"request"`
}

func (d *DataConstraintsResponse) GetInstitutionID() string {
	if d == nil {
		return ""
	}
	return d.InstitutionID
}

func (d *DataConstraintsResponse) GetInstitutionCountryCode() *string {
	if d == nil {
		return nil
	}
	return d.InstitutionCountryCode
}

func (d *DataConstraintsResponse) GetEndpointPath() *string {
	if d == nil {
		return nil
	}
	return d.EndpointPath
}

func (d *DataConstraintsResponse) GetEndpointMethod() *string {
	if d == nil {
		return nil
	}
	return d.EndpointMethod
}

func (d *DataConstraintsResponse) GetRequest() RequestConstraints {
	if d == nil {
		return RequestConstraints{}
	}
	return d.Request
}
