// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type EnumError string

const (
	EnumErrorMandatory     EnumError = "MANDATORY"
	EnumErrorInvalidFormat EnumError = "INVALID_FORMAT"
)

func (e EnumError) ToPointer() *EnumError {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *EnumError) IsExact() bool {
	if e != nil {
		switch *e {
		case "MANDATORY", "INVALID_FORMAT":
			return true
		}
	}
	return false
}
