// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type FilteredClientPayloadListDirectDebitResponse struct {
	APICall        *APICall                 `json:"apiCall,omitzero"`
	Data           []DirectDebitResponse    `json:"data,omitzero"`
	NextCursorHash *string                  `json:"nextCursorHash,omitzero"`
	NextLink       *string                  `json:"nextLink,omitzero"`
	PagingMap      map[string]FilterAndSort `json:"pagingMap,omitzero"`
	TotalCount     *int64                   `json:"totalCount,omitzero"`
}

func (f FilteredClientPayloadListDirectDebitResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *FilteredClientPayloadListDirectDebitResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *FilteredClientPayloadListDirectDebitResponse) GetAPICall() *APICall {
	if f == nil {
		return nil
	}
	return f.APICall
}

func (f *FilteredClientPayloadListDirectDebitResponse) GetData() []DirectDebitResponse {
	if f == nil {
		return nil
	}
	return f.Data
}

func (f *FilteredClientPayloadListDirectDebitResponse) GetNextCursorHash() *string {
	if f == nil {
		return nil
	}
	return f.NextCursorHash
}

func (f *FilteredClientPayloadListDirectDebitResponse) GetNextLink() *string {
	if f == nil {
		return nil
	}
	return f.NextLink
}

func (f *FilteredClientPayloadListDirectDebitResponse) GetPagingMap() map[string]FilterAndSort {
	if f == nil {
		return nil
	}
	return f.PagingMap
}

func (f *FilteredClientPayloadListDirectDebitResponse) GetTotalCount() *int64 {
	if f == nil {
		return nil
	}
	return f.TotalCount
}
