// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FrequencyResponse - __Mandatory__. Defines the intervals at which payment should be made.
type FrequencyResponse struct {
	// __Mandatory__. See [payment frequency](/guides/payments/payment-execution/periodic-payments/#payment-frequency) for more information
	FrequencyType *FrequencyEnumExtended `json:"frequencyType,omitzero"`
	// The weekly intervals at which a payment will be made. e.g. 1 = Every months, 2 = Every 2 months.
	IntervalWeek *int `json:"intervalWeek,omitzero"`
	// The monthly intervals at which a payment will be made. e.g. 1 = Every month, 2 = Every 2 months
	IntervalMonth *int `json:"intervalMonth,omitzero"`
	// The day on which a payment will be made, according to the weekly or monthly interval.
	ExecutionDay *int `json:"executionDay,omitzero"`
}

func (f *FrequencyResponse) GetFrequencyType() *FrequencyEnumExtended {
	if f == nil {
		return nil
	}
	return f.FrequencyType
}

func (f *FrequencyResponse) GetIntervalWeek() *int {
	if f == nil {
		return nil
	}
	return f.IntervalWeek
}

func (f *FrequencyResponse) GetIntervalMonth() *int {
	if f == nil {
		return nil
	}
	return f.IntervalMonth
}

func (f *FrequencyResponse) GetExecutionDay() *int {
	if f == nil {
		return nil
	}
	return f.ExecutionDay
}
