// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

type HostedGetConsentRequestResponse struct {
	// Unique Id of the consent request.
	ConsentRequestID *string `json:"consentRequestId,omitzero"`
	// Identification of the consent.
	ConsentID *string `json:"consentId,omitzero"`
	// Unique Id for the `User` assigned by Yapily.
	UserID *string `json:"userId,omitzero"`
	// Your reference to the `User`.
	ApplicationUserID *string `json:"applicationUserId,omitzero"`
	// Unique Id of the `Application` the user is associated with.
	ApplicationID *string `json:"applicationId,omitzero"`
	// Specifies the institution selected for making the payment.
	InstitutionIdentifiers *InstitutionIdentifiersResponse `json:"institutionIdentifiers,omitzero"`
	// Specifies the language and location preferences of the user.
	UserSettings *UserSettings `json:"userSettings,omitzero"`
	// URL of consent server to redirect the user after completion of the consent flow.
	RedirectURL *string `json:"redirectUrl,omitzero"`
	// The date and time at which the payment was created.
	CreatedAt *time.Time `json:"createdAt,omitzero"`
	// The date and time at which the auth Token will expire.
	AuthorisationExpiresAt *time.Time `json:"authorisationExpiresAt,omitzero"`
	// Current status of the consent request. Allowed values are [AWAITING_AUTHORIZATION, AUTHORIZED, REJECTED, REVOKED, FAILED, EXPIRED, AWAITING_DECOUPLED_AUTHORIZATION]
	Status *string `json:"status,omitzero"`
	// The phase reached by the consent and its timestamp.
	Phases []HostedConsentPhase `json:"phases,omitzero"`
	// Represents the authorisation to gain access to the requested features. Required to access account information.
	ConsentToken *string `json:"consentToken,omitzero"`
}

func (h HostedGetConsentRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HostedGetConsentRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HostedGetConsentRequestResponse) GetConsentRequestID() *string {
	if h == nil {
		return nil
	}
	return h.ConsentRequestID
}

func (h *HostedGetConsentRequestResponse) GetConsentID() *string {
	if h == nil {
		return nil
	}
	return h.ConsentID
}

func (h *HostedGetConsentRequestResponse) GetUserID() *string {
	if h == nil {
		return nil
	}
	return h.UserID
}

func (h *HostedGetConsentRequestResponse) GetApplicationUserID() *string {
	if h == nil {
		return nil
	}
	return h.ApplicationUserID
}

func (h *HostedGetConsentRequestResponse) GetApplicationID() *string {
	if h == nil {
		return nil
	}
	return h.ApplicationID
}

func (h *HostedGetConsentRequestResponse) GetInstitutionIdentifiers() *InstitutionIdentifiersResponse {
	if h == nil {
		return nil
	}
	return h.InstitutionIdentifiers
}

func (h *HostedGetConsentRequestResponse) GetUserSettings() *UserSettings {
	if h == nil {
		return nil
	}
	return h.UserSettings
}

func (h *HostedGetConsentRequestResponse) GetRedirectURL() *string {
	if h == nil {
		return nil
	}
	return h.RedirectURL
}

func (h *HostedGetConsentRequestResponse) GetCreatedAt() *time.Time {
	if h == nil {
		return nil
	}
	return h.CreatedAt
}

func (h *HostedGetConsentRequestResponse) GetAuthorisationExpiresAt() *time.Time {
	if h == nil {
		return nil
	}
	return h.AuthorisationExpiresAt
}

func (h *HostedGetConsentRequestResponse) GetStatus() *string {
	if h == nil {
		return nil
	}
	return h.Status
}

func (h *HostedGetConsentRequestResponse) GetPhases() []HostedConsentPhase {
	if h == nil {
		return nil
	}
	return h.Phases
}

func (h *HostedGetConsentRequestResponse) GetConsentToken() *string {
	if h == nil {
		return nil
	}
	return h.ConsentToken
}
