// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type HostedPayment struct {
	// The Unique Identifier of the payment.
	PaymentID *string `json:"paymentId,omitzero"`
	// The Unique Identifier of the payment created using Yapily hosted application.
	HostedPaymentID *string `json:"hostedPaymentId,omitzero"`
	// The Unique Identifier of the consent.
	ConsentID *string `json:"consentId,omitzero"`
	// Specifies the institution selected for making the payment.
	InstitutionIdentifiers *InstitutionIdentifiersResponse `json:"institutionIdentifiers,omitzero"`
	// The phase reached by the payment and its timestamp.
	Phases []HostedPaymentPhase `json:"phases,omitzero"`
	// Payment status based on latest HostedAuthPaymentPhase in phases. Value can be
	//
	// - PENDING  -  Payment pending processing
	// - COMPLETED  -  Payment processing completed
	// - FAILED  -  Payment process failed
	PaymentStatus *string `json:"paymentStatus,omitzero"`
	// Details of the payment status.
	StatusDetails []HostedPaymentStatusDetails `json:"statusDetails,omitzero"`
	// The Unique Identifier of the payment created with the `Institution`.
	InstitutionPaymentID *string `json:"institutionPaymentId,omitzero"`
	// The Unique Identifier provided by TPP in the Payment request to identify the payment.
	PaymentLifecycleID *string `json:"paymentLifecycleId,omitzero"`
	// A unique identifier that you must provide to identify the payment. This can be any alpha-numeric string but is limited to a maximum of 35 characters.
	PaymentIdempotencyID *string `json:"paymentIdempotencyId,omitzero"`
	// The payment reference or description. Limited to a maximum of 18 characters for UK institutions.
	Reference *string `json:"reference,omitzero"`
	// The payment context code.
	ContextType *PaymentContextTypeResponse `json:"contextType,omitzero"`
	// Specifies which of the [payment types](/payments/payment-resources/intro-to-payment-execution#payment-types) to execute.
	Type *PaymentTypeResponse `json:"type,omitzero"`
	//  Details of the beneficiary [person or business].
	Payee *PayeeDetailsResponse `json:"payee,omitzero"`
	// Details of the benefactor [person or business].
	Payer *PayerDetailsResponse `json:"payer,omitzero"`
	// Monetary Amount.
	Amount *AmountDetailsResponse `json:"amount,omitzero"`
}

func (h HostedPayment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HostedPayment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HostedPayment) GetPaymentID() *string {
	if h == nil {
		return nil
	}
	return h.PaymentID
}

func (h *HostedPayment) GetHostedPaymentID() *string {
	if h == nil {
		return nil
	}
	return h.HostedPaymentID
}

func (h *HostedPayment) GetConsentID() *string {
	if h == nil {
		return nil
	}
	return h.ConsentID
}

func (h *HostedPayment) GetInstitutionIdentifiers() *InstitutionIdentifiersResponse {
	if h == nil {
		return nil
	}
	return h.InstitutionIdentifiers
}

func (h *HostedPayment) GetPhases() []HostedPaymentPhase {
	if h == nil {
		return nil
	}
	return h.Phases
}

func (h *HostedPayment) GetPaymentStatus() *string {
	if h == nil {
		return nil
	}
	return h.PaymentStatus
}

func (h *HostedPayment) GetStatusDetails() []HostedPaymentStatusDetails {
	if h == nil {
		return nil
	}
	return h.StatusDetails
}

func (h *HostedPayment) GetInstitutionPaymentID() *string {
	if h == nil {
		return nil
	}
	return h.InstitutionPaymentID
}

func (h *HostedPayment) GetPaymentLifecycleID() *string {
	if h == nil {
		return nil
	}
	return h.PaymentLifecycleID
}

func (h *HostedPayment) GetPaymentIdempotencyID() *string {
	if h == nil {
		return nil
	}
	return h.PaymentIdempotencyID
}

func (h *HostedPayment) GetReference() *string {
	if h == nil {
		return nil
	}
	return h.Reference
}

func (h *HostedPayment) GetContextType() *PaymentContextTypeResponse {
	if h == nil {
		return nil
	}
	return h.ContextType
}

func (h *HostedPayment) GetType() *PaymentTypeResponse {
	if h == nil {
		return nil
	}
	return h.Type
}

func (h *HostedPayment) GetPayee() *PayeeDetailsResponse {
	if h == nil {
		return nil
	}
	return h.Payee
}

func (h *HostedPayment) GetPayer() *PayerDetailsResponse {
	if h == nil {
		return nil
	}
	return h.Payer
}

func (h *HostedPayment) GetAmount() *AmountDetailsResponse {
	if h == nil {
		return nil
	}
	return h.Amount
}
