// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// HostedVrpInitiationDetails - __Optional__. The details of the participating parties.
type HostedVrpInitiationDetails struct {
	// The reference/description of the payments that will be carried out on this VRP consent.
	Reference *string `json:"reference,omitzero"`
	// __Conditional__. Details of the benefactor [person or business].
	Payer         *Payer            `json:"payer,omitzero"`
	UltimatePayer *VrpUltimatePayer `json:"ultimatePayer,omitzero"`
	// __Mandatory__. Details of the beneficiary [person or business].
	Payee         *Payee            `json:"payee,omitzero"`
	UltimatePayee *VrpUltimatePayee `json:"ultimatePayee,omitzero"`
}

func (h HostedVrpInitiationDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HostedVrpInitiationDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HostedVrpInitiationDetails) GetReference() *string {
	if h == nil {
		return nil
	}
	return h.Reference
}

func (h *HostedVrpInitiationDetails) GetPayer() *Payer {
	if h == nil {
		return nil
	}
	return h.Payer
}

func (h *HostedVrpInitiationDetails) GetUltimatePayer() *VrpUltimatePayer {
	if h == nil {
		return nil
	}
	return h.UltimatePayer
}

func (h *HostedVrpInitiationDetails) GetPayee() *Payee {
	if h == nil {
		return nil
	}
	return h.Payee
}

func (h *HostedVrpInitiationDetails) GetUltimatePayee() *VrpUltimatePayee {
	if h == nil {
		return nil
	}
	return h.UltimatePayee
}
