// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

// HostedPaymentPhase - The phase of the payment.
type HostedPaymentPhase struct {
	// The name of the hosted payment process phase. Allowed values are :
	//
	// - INITIATED - Payment process initiated
	// - DECLINED - Payment process failed and will not proceed further
	// - INSTITUTION_SUBMITTED - Payment institution submitted
	// - EMBEDDED_CREDENTIAL_REQUESTED - For embedded banks, a UI element to collect user credentials was displayed
	// - CREDENTIALS_ERROR - embedded credentials refused by institution
	// - AUTHORISATION_INITIATED - All details required for payment initiation have been collected
	// - VALIDATION_COMPLETED - The payment payload was validated successfully
	// - VALIDATION_FAILED - The payment data provided failed validation
	// - AUTHORISATION_CREATED - Payment authorisation request created with Institution
	// - EMBEDDED_CODE_REQUESTED - For embedded banks, a UI element to collect SCA for initiated consent was displayed
	// - EMBEDDED_TYPE_REQUESTED - For embedded banks, a UI element to allow the user to select their preferred SCA method for this consent authorisation was displayed
	// - DECOUPLED_AUTHORISATION - For embedded banks, decoupled authorisation was initiated by the bank
	// - EMBEDDED_CODE_COLLECTED - For embedded banks, SCA code was collected for consent authorisation
	// - EMBEDDED_TYPE_SELECTED - For embedded banks, preferred SCA method was selected for consent authorisation
	// - PRE_AUTHORISED - pre authorisation was initiated by bank
	// - CONSENT_POLLING_STARTED - We start polling the bank for consent authorisation status
	// - CONSENT_POLLING_ENDED - We finish polling the bank for consent authorisation status
	// - AUTHORISED - Payment authorisation completed
	// - AUTHORISATION_FAILED - Payment authorisation failed and will not proceed further
	// - AUTHORISATION_REJECTED - Payment authorisation rejected and will not proceed further
	// - SUBMITTED - Payment execution created and submitted to Institution
	// - SUBMITTED_AUTO - Payment execution created and submitted to Institution
	// - ACCEPTED - Payment execution accepted by Institution and awaiting settlement
	// - REJECTED - Payment or Authorisation request rejected by Institution and will not proceed further
	// - SETTLEMENT_COMPLETED - Payment settlement completed
	// - STATUS_POLLING_STARTED - Payment status polling started
	// - STATUS_POLLING_ENDED - Payment status polling ended
	// - MERCHANT_ACKNOWLEDGED - Payment acknowledgement received from merchant
	// - FINISHED - Payment process completed
	PhaseName *string `json:"phaseName,omitzero"`
	// The date and time when phase of the hosted payment was inserted.
	PhaseCreatedAt *time.Time `json:"phaseCreatedAt,omitzero"`
}

func (h HostedPaymentPhase) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HostedPaymentPhase) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HostedPaymentPhase) GetPhaseName() *string {
	if h == nil {
		return nil
	}
	return h.PhaseName
}

func (h *HostedPaymentPhase) GetPhaseCreatedAt() *time.Time {
	if h == nil {
		return nil
	}
	return h.PhaseCreatedAt
}
