// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// Identity - Identification details of a party associated with an account e.g. (account owner or operator).
type Identity struct {
	ID        *string           `json:"id,omitzero"`
	FirstName *string           `json:"firstName,omitzero"`
	LastName  *string           `json:"lastName,omitzero"`
	FullName  *string           `json:"fullName,omitzero"`
	Gender    *string           `json:"gender,omitzero"`
	Birthdate *string           `json:"birthdate,omitzero"`
	Email     *string           `json:"email,omitzero"`
	Phone     *string           `json:"phone,omitzero"`
	Addresses []IdentityAddress `json:"addresses,omitzero"`
}

func (i Identity) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Identity) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Identity) GetID() *string {
	if i == nil {
		return nil
	}
	return i.ID
}

func (i *Identity) GetFirstName() *string {
	if i == nil {
		return nil
	}
	return i.FirstName
}

func (i *Identity) GetLastName() *string {
	if i == nil {
		return nil
	}
	return i.LastName
}

func (i *Identity) GetFullName() *string {
	if i == nil {
		return nil
	}
	return i.FullName
}

func (i *Identity) GetGender() *string {
	if i == nil {
		return nil
	}
	return i.Gender
}

func (i *Identity) GetBirthdate() *string {
	if i == nil {
		return nil
	}
	return i.Birthdate
}

func (i *Identity) GetEmail() *string {
	if i == nil {
		return nil
	}
	return i.Email
}

func (i *Identity) GetPhone() *string {
	if i == nil {
		return nil
	}
	return i.Phone
}

func (i *Identity) GetAddresses() []IdentityAddress {
	if i == nil {
		return nil
	}
	return i.Addresses
}
