// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type IdentityAddress struct {
	AddressLines   []string `json:"addressLines,omitzero"`
	City           *string  `json:"city,omitzero"`
	PostalCode     *string  `json:"postalCode,omitzero"`
	Country        *string  `json:"country,omitzero"`
	StreetName     *string  `json:"streetName,omitzero"`
	BuildingNumber *string  `json:"buildingNumber,omitzero"`
	// __Optional__. The type of address
	Type   *AddressTypeEnum `json:"type,omitzero"`
	County *string          `json:"county,omitzero"`
}

func (i IdentityAddress) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IdentityAddress) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IdentityAddress) GetAddressLines() []string {
	if i == nil {
		return nil
	}
	return i.AddressLines
}

func (i *IdentityAddress) GetCity() *string {
	if i == nil {
		return nil
	}
	return i.City
}

func (i *IdentityAddress) GetPostalCode() *string {
	if i == nil {
		return nil
	}
	return i.PostalCode
}

func (i *IdentityAddress) GetCountry() *string {
	if i == nil {
		return nil
	}
	return i.Country
}

func (i *IdentityAddress) GetStreetName() *string {
	if i == nil {
		return nil
	}
	return i.StreetName
}

func (i *IdentityAddress) GetBuildingNumber() *string {
	if i == nil {
		return nil
	}
	return i.BuildingNumber
}

func (i *IdentityAddress) GetType() *AddressTypeEnum {
	if i == nil {
		return nil
	}
	return i.Type
}

func (i *IdentityAddress) GetCounty() *string {
	if i == nil {
		return nil
	}
	return i.County
}
