// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// InstitutionIdentifiersResponse - Specifies the institution selected for making the payment.
type InstitutionIdentifiersResponse struct {
	// Yapily identifier which identifies the `Institution` the payment request is sent to.
	InstitutionID *string `json:"institutionId,omitzero"`
	// 2 letter ISO Country code of the `Institution` the payment request is sent to.
	InstitutionCountryCode *string `json:"institutionCountryCode,omitzero"`
}

func (i *InstitutionIdentifiersResponse) GetInstitutionID() *string {
	if i == nil {
		return nil
	}
	return i.InstitutionID
}

func (i *InstitutionIdentifiersResponse) GetInstitutionCountryCode() *string {
	if i == nil {
		return nil
	}
	return i.InstitutionCountryCode
}
