// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// IsoBankTransactionCode - Defines the underlying transaction type (e.g. Card or Debit Transactions, Loans or Mortages).
//
//	Conforms to `ISO` standards - ISO 20022.
type IsoBankTransactionCode struct {
	// __Mandatory__. Details the identification of the ISO code.
	DomainCode *IsoCodeDetails `json:"domainCode,omitzero"`
	// __Mandatory__. Details the identification of the ISO code.
	FamilyCode *IsoCodeDetails `json:"familyCode,omitzero"`
	// __Mandatory__. Details the identification of the ISO code.
	SubFamilyCode *IsoCodeDetails `json:"subFamilyCode,omitzero"`
}

func (i IsoBankTransactionCode) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IsoBankTransactionCode) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IsoBankTransactionCode) GetDomainCode() *IsoCodeDetails {
	if i == nil {
		return nil
	}
	return i.DomainCode
}

func (i *IsoBankTransactionCode) GetFamilyCode() *IsoCodeDetails {
	if i == nil {
		return nil
	}
	return i.FamilyCode
}

func (i *IsoBankTransactionCode) GetSubFamilyCode() *IsoCodeDetails {
	if i == nil {
		return nil
	}
	return i.SubFamilyCode
}
