// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

// MultiAuthorisation - Details the additional levels of authorisation which are required from, and being managed by, the `Institution`.
type MultiAuthorisation struct {
	// __Mandatory__. Specifies the current status of the multi-authorisation flow.
	Status *string `json:"status,omitzero"`
	// __Mandatory__. Total number of authorisations required.
	NumberOfAuthorisationRequired *int `json:"numberOfAuthorisationRequired,omitzero"`
	// __Mandatory__. The total number of authorisations that have been received.
	NumberOfAuthorisationReceived *int `json:"numberOfAuthorisationReceived,omitzero"`
	// __Mandatory__. Date and time of when the authorisation was last updated.
	LastUpdatedDateTime *time.Time `json:"lastUpdatedDateTime,omitzero"`
	// __Mandatory__. Date and time by when the authorisation flow must be completed before it expires and the authorisation request is terminated.
	ExpirationDateTime *time.Time `json:"expirationDateTime,omitzero"`
}

func (m MultiAuthorisation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(m, "", false)
}

func (m *MultiAuthorisation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &m, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (m *MultiAuthorisation) GetStatus() *string {
	if m == nil {
		return nil
	}
	return m.Status
}

func (m *MultiAuthorisation) GetNumberOfAuthorisationRequired() *int {
	if m == nil {
		return nil
	}
	return m.NumberOfAuthorisationRequired
}

func (m *MultiAuthorisation) GetNumberOfAuthorisationReceived() *int {
	if m == nil {
		return nil
	}
	return m.NumberOfAuthorisationReceived
}

func (m *MultiAuthorisation) GetLastUpdatedDateTime() *time.Time {
	if m == nil {
		return nil
	}
	return m.LastUpdatedDateTime
}

func (m *MultiAuthorisation) GetExpirationDateTime() *time.Time {
	if m == nil {
		return nil
	}
	return m.ExpirationDateTime
}
