// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type Pagination struct {
	TotalCount *int64         `json:"totalCount,omitzero"`
	Self       *FilterAndSort `json:"self,omitzero"`
	Next       *Next          `json:"next,omitzero"`
}

func (p Pagination) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Pagination) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *Pagination) GetTotalCount() *int64 {
	if p == nil {
		return nil
	}
	return p.TotalCount
}

func (p *Pagination) GetSelf() *FilterAndSort {
	if p == nil {
		return nil
	}
	return p.Self
}

func (p *Pagination) GetNext() *Next {
	if p == nil {
		return nil
	}
	return p.Next
}
