// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PayerDetails - __Conditional__. Details of the benefactor [person or business].
type PayerDetails struct {
	// __Mandatory__. The account identifications that identify the `Payer` bank account.
	AccountIdentifications []AccountIdentification `json:"accountIdentifications"`
}

func (p *PayerDetails) GetAccountIdentifications() []AccountIdentification {
	if p == nil {
		return []AccountIdentification{}
	}
	return p.AccountIdentifications
}
