// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

type PaymentEmbeddedAuthorisationRequestResponse struct {
	// Unique identifier for the embedded payment authorisation request.
	ID *string `json:"id,omitzero"`
	// The `User` that the authorisation request was created for.
	UserUUID *string `json:"userUuid,omitzero"`
	// The user-friendly reference to the `User` that the authorisation request was created for.
	ApplicationUserID *string `json:"applicationUserId,omitzero"`
	ReferenceID       *string `json:"referenceId,omitzero"`
	// The  `Institution` the authorisation request was sent to.
	InstitutionID *string `json:"institutionId,omitzero"`
	// Current status of the embedded authorisation request in code form.
	Status *AuthorisationStatus `json:"status,omitzero"`
	// Date and time the embedded payment authorisation was created.
	CreatedAt *time.Time `json:"createdAt,omitzero"`
	// When performing a transaction query using the consent, this is the earliest date of transaction records that can be retrieved.
	TransactionFrom *time.Time `json:"transactionFrom,omitzero"`
	// When performing a transaction query using the consent, this is the latest date of transaction records that can be retrieved.
	TransactionTo *time.Time `json:"transactionTo,omitzero"`
	// Date and time the authorisation expires. Re-authorisation is needed to retain access.
	ExpiresAt *time.Time `json:"expiresAt,omitzero"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TimeToExpireInMillis *int64  `json:"timeToExpireInMillis,omitzero"`
	TimeToExpire         *string `json:"timeToExpire,omitzero"`
	// The set of features the consent provides access to.
	FeatureScope []FeatureEnum `json:"featureScope,omitzero"`
	// Represents the authorisation to gain access to the requested features. Required to make a payment request.
	ConsentToken *string `json:"consentToken,omitzero"`
	// Correlation ID used with the `Institution` during the authorisation process.
	State *string `json:"state,omitzero"`
	// Date and time the request was authorised by the `Institution`.
	AuthorizedAt *time.Time `json:"authorizedAt,omitzero"`
	// Identification of the consent at the `Institution`.
	InstitutionConsentID    *string                          `json:"institutionConsentId,omitzero"`
	Charges                 []PaymentChargeDetails           `json:"charges,omitzero"`
	ExchangeRateInformation *ExchangeRateInformationResponse `json:"exchangeRateInformation,omitzero"`
	AuthorisationURL        *string                          `json:"authorisationUrl,omitzero"`
	// The URL link for the QR code that may be scanned via a mobile device to make an authorisation redirect to the bank (authURL encoded).
	QrCodeURL   *string     `json:"qrCodeUrl,omitzero"`
	Explanation *string     `json:"explanation,omitzero"`
	ScaMethods  []ScaMethod `json:"scaMethods,omitzero"`
	// __Conditional__. Used to update the authorisation with the sca method of the user's choice for the `Institution` that uses the embedded authorisation flow. If the user has multiple sca methods configured, the `Institution` will allow the user to select from each of these options.
	//
	// When the user has multiple sca methods for the `Institution`, this is the second step required in the embedded authorisation flow to authorise the `Consent`.
	SelectedScaMethod *ScaMethod `json:"selectedScaMethod,omitzero"`
}

func (p PaymentEmbeddedAuthorisationRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetID() *string {
	if p == nil {
		return nil
	}
	return p.ID
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetUserUUID() *string {
	if p == nil {
		return nil
	}
	return p.UserUUID
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetApplicationUserID() *string {
	if p == nil {
		return nil
	}
	return p.ApplicationUserID
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetReferenceID() *string {
	if p == nil {
		return nil
	}
	return p.ReferenceID
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetInstitutionID() *string {
	if p == nil {
		return nil
	}
	return p.InstitutionID
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetStatus() *AuthorisationStatus {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetCreatedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.CreatedAt
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetTransactionFrom() *time.Time {
	if p == nil {
		return nil
	}
	return p.TransactionFrom
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetTransactionTo() *time.Time {
	if p == nil {
		return nil
	}
	return p.TransactionTo
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetExpiresAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.ExpiresAt
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetTimeToExpireInMillis() *int64 {
	if p == nil {
		return nil
	}
	return p.TimeToExpireInMillis
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetTimeToExpire() *string {
	if p == nil {
		return nil
	}
	return p.TimeToExpire
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetFeatureScope() []FeatureEnum {
	if p == nil {
		return nil
	}
	return p.FeatureScope
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetConsentToken() *string {
	if p == nil {
		return nil
	}
	return p.ConsentToken
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetState() *string {
	if p == nil {
		return nil
	}
	return p.State
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetAuthorizedAt() *time.Time {
	if p == nil {
		return nil
	}
	return p.AuthorizedAt
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetInstitutionConsentID() *string {
	if p == nil {
		return nil
	}
	return p.InstitutionConsentID
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetCharges() []PaymentChargeDetails {
	if p == nil {
		return nil
	}
	return p.Charges
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetExchangeRateInformation() *ExchangeRateInformationResponse {
	if p == nil {
		return nil
	}
	return p.ExchangeRateInformation
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetAuthorisationURL() *string {
	if p == nil {
		return nil
	}
	return p.AuthorisationURL
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetQrCodeURL() *string {
	if p == nil {
		return nil
	}
	return p.QrCodeURL
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetExplanation() *string {
	if p == nil {
		return nil
	}
	return p.Explanation
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetScaMethods() []ScaMethod {
	if p == nil {
		return nil
	}
	return p.ScaMethods
}

func (p *PaymentEmbeddedAuthorisationRequestResponse) GetSelectedScaMethod() *ScaMethod {
	if p == nil {
		return nil
	}
	return p.SelectedScaMethod
}
