// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// PaymentChargeDetails - Details the charges that will apply to the payment.
type PaymentChargeDetails struct {
	// __Mandatory__. Monetary Amount.
	ChargeAmount *Amount `json:"chargeAmount,omitzero"`
	// __Mandatory__. Specifies the nature of the transaction charge e.g. (Bank transfer fees).
	ChargeType *string `json:"chargeType,omitzero"`
	// __Mandatory__. States which party of the payment bears the charges.
	ChargeTo *string `json:"chargeTo,omitzero"`
}

func (p PaymentChargeDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentChargeDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentChargeDetails) GetChargeAmount() *Amount {
	if p == nil {
		return nil
	}
	return p.ChargeAmount
}

func (p *PaymentChargeDetails) GetChargeType() *string {
	if p == nil {
		return nil
	}
	return p.ChargeType
}

func (p *PaymentChargeDetails) GetChargeTo() *string {
	if p == nil {
		return nil
	}
	return p.ChargeTo
}
