// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaymentTypeResponse - Specifies which of the [payment types](/payments/payment-resources/intro-to-payment-execution#payment-types) to execute.
type PaymentTypeResponse string

const (
	PaymentTypeResponseDomesticPayment                  PaymentTypeResponse = "DOMESTIC_PAYMENT"
	PaymentTypeResponseDomesticInstantPayment           PaymentTypeResponse = "DOMESTIC_INSTANT_PAYMENT"
	PaymentTypeResponseDomesticVariableRecurringPayment PaymentTypeResponse = "DOMESTIC_VARIABLE_RECURRING_PAYMENT"
	PaymentTypeResponseDomesticScheduledPayment         PaymentTypeResponse = "DOMESTIC_SCHEDULED_PAYMENT"
	PaymentTypeResponseDomesticPeriodicPayment          PaymentTypeResponse = "DOMESTIC_PERIODIC_PAYMENT"
	PaymentTypeResponseInternationalPayment             PaymentTypeResponse = "INTERNATIONAL_PAYMENT"
	PaymentTypeResponseInternationalScheduledPayment    PaymentTypeResponse = "INTERNATIONAL_SCHEDULED_PAYMENT"
	PaymentTypeResponseInternationalPeriodicPayment     PaymentTypeResponse = "INTERNATIONAL_PERIODIC_PAYMENT"
)

func (e PaymentTypeResponse) ToPointer() *PaymentTypeResponse {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PaymentTypeResponse) IsExact() bool {
	if e != nil {
		switch *e {
		case "DOMESTIC_PAYMENT", "DOMESTIC_INSTANT_PAYMENT", "DOMESTIC_VARIABLE_RECURRING_PAYMENT", "DOMESTIC_SCHEDULED_PAYMENT", "DOMESTIC_PERIODIC_PAYMENT", "INTERNATIONAL_PAYMENT", "INTERNATIONAL_SCHEDULED_PAYMENT", "INTERNATIONAL_PERIODIC_PAYMENT":
			return true
		}
	}
	return false
}
