// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

type PaymentStatusDetails struct {
	// The status of the Payment.
	//
	// For more information, see [Payment Status](/guides/payments/payment-status/)
	Status                  *PaymentStatus `json:"status,omitzero"`
	StatusReason            *string        `json:"statusReason,omitzero"`
	StatusReasonDescription *string        `json:"statusReasonDescription,omitzero"`
	StatusUpdateDate        *time.Time     `json:"statusUpdateDate,omitzero"`
	// Details the additional levels of authorisation which are required from, and being managed by, the `Institution`.
	MultiAuthorisationStatus *MultiAuthorisation `json:"multiAuthorisationStatus,omitzero"`
	// The payment status code, as denoted by a 3-letter ISO 20022 code.
	IsoStatus *PaymentIsoStatus `json:"isoStatus,omitzero"`
}

func (p PaymentStatusDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PaymentStatusDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PaymentStatusDetails) GetStatus() *PaymentStatus {
	if p == nil {
		return nil
	}
	return p.Status
}

func (p *PaymentStatusDetails) GetStatusReason() *string {
	if p == nil {
		return nil
	}
	return p.StatusReason
}

func (p *PaymentStatusDetails) GetStatusReasonDescription() *string {
	if p == nil {
		return nil
	}
	return p.StatusReasonDescription
}

func (p *PaymentStatusDetails) GetStatusUpdateDate() *time.Time {
	if p == nil {
		return nil
	}
	return p.StatusUpdateDate
}

func (p *PaymentStatusDetails) GetMultiAuthorisationStatus() *MultiAuthorisation {
	if p == nil {
		return nil
	}
	return p.MultiAuthorisationStatus
}

func (p *PaymentStatusDetails) GetIsoStatus() *PaymentIsoStatus {
	if p == nil {
		return nil
	}
	return p.IsoStatus
}
