// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// PaymentType - __Mandatory__. Used to specify which of the [payment types](/payments/payment-resources/intro-to-payment-execution#payment-types) to execute.
//
// See [European Payments](/payments/payment-resources/european-payments) to verify whether the `type` should be `DOMESTIC` or `INTERNATIONAL`.
type PaymentType string

const (
	PaymentTypeDomesticPayment                  PaymentType = "DOMESTIC_PAYMENT"
	PaymentTypeDomesticInstantPayment           PaymentType = "DOMESTIC_INSTANT_PAYMENT"
	PaymentTypeDomesticVariableRecurringPayment PaymentType = "DOMESTIC_VARIABLE_RECURRING_PAYMENT"
	PaymentTypeDomesticScheduledPayment         PaymentType = "DOMESTIC_SCHEDULED_PAYMENT"
	PaymentTypeDomesticPeriodicPayment          PaymentType = "DOMESTIC_PERIODIC_PAYMENT"
	PaymentTypeInternationalPayment             PaymentType = "INTERNATIONAL_PAYMENT"
	PaymentTypeInternationalScheduledPayment    PaymentType = "INTERNATIONAL_SCHEDULED_PAYMENT"
	PaymentTypeInternationalPeriodicPayment     PaymentType = "INTERNATIONAL_PERIODIC_PAYMENT"
	PaymentTypeBulkPayment                      PaymentType = "BULK_PAYMENT"
)

func (e PaymentType) ToPointer() *PaymentType {
	return &e
}
func (e *PaymentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DOMESTIC_PAYMENT":
		fallthrough
	case "DOMESTIC_INSTANT_PAYMENT":
		fallthrough
	case "DOMESTIC_VARIABLE_RECURRING_PAYMENT":
		fallthrough
	case "DOMESTIC_SCHEDULED_PAYMENT":
		fallthrough
	case "DOMESTIC_PERIODIC_PAYMENT":
		fallthrough
	case "INTERNATIONAL_PAYMENT":
		fallthrough
	case "INTERNATIONAL_SCHEDULED_PAYMENT":
		fallthrough
	case "INTERNATIONAL_PERIODIC_PAYMENT":
		fallthrough
	case "BULK_PAYMENT":
		*e = PaymentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentType: %v", v)
	}
}
