// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// PaymentIsoStatusCodeEnum - The ISO 20022 `PaymentStatusCode`.
type PaymentIsoStatusCodeEnum string

const (
	PaymentIsoStatusCodeEnumAccc PaymentIsoStatusCodeEnum = "ACCC"
	PaymentIsoStatusCodeEnumAccp PaymentIsoStatusCodeEnum = "ACCP"
	PaymentIsoStatusCodeEnumAcsc PaymentIsoStatusCodeEnum = "ACSC"
	PaymentIsoStatusCodeEnumAcsp PaymentIsoStatusCodeEnum = "ACSP"
	PaymentIsoStatusCodeEnumActc PaymentIsoStatusCodeEnum = "ACTC"
	PaymentIsoStatusCodeEnumAcwc PaymentIsoStatusCodeEnum = "ACWC"
	PaymentIsoStatusCodeEnumAcwp PaymentIsoStatusCodeEnum = "ACWP"
	PaymentIsoStatusCodeEnumRcvd PaymentIsoStatusCodeEnum = "RCVD"
	PaymentIsoStatusCodeEnumPdng PaymentIsoStatusCodeEnum = "PDNG"
	PaymentIsoStatusCodeEnumRjct PaymentIsoStatusCodeEnum = "RJCT"
	PaymentIsoStatusCodeEnumCanc PaymentIsoStatusCodeEnum = "CANC"
	PaymentIsoStatusCodeEnumAcfc PaymentIsoStatusCodeEnum = "ACFC"
	PaymentIsoStatusCodeEnumPatc PaymentIsoStatusCodeEnum = "PATC"
	PaymentIsoStatusCodeEnumPart PaymentIsoStatusCodeEnum = "PART"
	PaymentIsoStatusCodeEnumAcco PaymentIsoStatusCodeEnum = "ACCO"
)

func (e PaymentIsoStatusCodeEnum) ToPointer() *PaymentIsoStatusCodeEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *PaymentIsoStatusCodeEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "ACCC", "ACCP", "ACSC", "ACSP", "ACTC", "ACWC", "ACWP", "RCVD", "PDNG", "RJCT", "CANC", "ACFC", "PATC", "PART", "ACCO":
			return true
		}
	}
	return false
}
