// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type Result struct {
}

// RawResponse - [DEPRECATED] Interaction (raw request and response) that occurred with the `Institution` in order to fulfil a request.
//
// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
type RawResponse struct {
	Request    *RawRequest       `json:"request,omitzero"`
	Duration   *string           `json:"duration,omitzero"`
	Headers    map[string]string `json:"headers,omitzero"`
	ResultCode *int              `json:"resultCode,omitzero"`
	Result     *Result           `json:"result,omitzero"`
}

func (r RawResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RawResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RawResponse) GetRequest() *RawRequest {
	if r == nil {
		return nil
	}
	return r.Request
}

func (r *RawResponse) GetDuration() *string {
	if r == nil {
		return nil
	}
	return r.Duration
}

func (r *RawResponse) GetHeaders() map[string]string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *RawResponse) GetResultCode() *int {
	if r == nil {
		return nil
	}
	return r.ResultCode
}

func (r *RawResponse) GetResult() *Result {
	if r == nil {
		return nil
	}
	return r.Result
}
