// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

type Body struct {
}

type RawRequest struct {
	Method         *string           `json:"method,omitzero"`
	URL            *string           `json:"url,omitzero"`
	RequestInstant *time.Time        `json:"requestInstant,omitzero"`
	Headers        map[string]string `json:"headers,omitzero"`
	Body           *Body             `json:"body,omitzero"`
	BodyParameters map[string]string `json:"bodyParameters,omitzero"`
	StartTime      *time.Time        `json:"startTime,omitzero"`
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	StartedAt *time.Time `json:"startedAt,omitzero"`
}

func (r RawRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RawRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RawRequest) GetMethod() *string {
	if r == nil {
		return nil
	}
	return r.Method
}

func (r *RawRequest) GetURL() *string {
	if r == nil {
		return nil
	}
	return r.URL
}

func (r *RawRequest) GetRequestInstant() *time.Time {
	if r == nil {
		return nil
	}
	return r.RequestInstant
}

func (r *RawRequest) GetHeaders() map[string]string {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *RawRequest) GetBody() *Body {
	if r == nil {
		return nil
	}
	return r.Body
}

func (r *RawRequest) GetBodyParameters() map[string]string {
	if r == nil {
		return nil
	}
	return r.BodyParameters
}

func (r *RawRequest) GetStartTime() *time.Time {
	if r == nil {
		return nil
	}
	return r.StartTime
}

func (r *RawRequest) GetStartedAt() *time.Time {
	if r == nil {
		return nil
	}
	return r.StartedAt
}
