// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// RedirectRequest - __Optional__. The server to redirect the user to after the user complete the authorisation at the `Institution`.
type RedirectRequest struct {
	// __Mandatory__.Successful redirect after the user complete the authorisation at the `Institution`.
	URL string `json:"url"`
}

func (r *RedirectRequest) GetURL() string {
	if r == nil {
		return ""
	}
	return r.URL
}
