// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// RegisteredWebhookWithStatusMain - Primary URL where events will be sent
type RegisteredWebhookWithStatusMain struct {
	URL *string `json:"url,omitzero"`
}

func (r *RegisteredWebhookWithStatusMain) GetURL() *string {
	if r == nil {
		return nil
	}
	return r.URL
}

// RegisteredWebhookWithStatusBackup - Secondary URL where events will be sent whenever the primary URL is not responding
type RegisteredWebhookWithStatusBackup struct {
	URL *string `json:"url,omitzero"`
}

func (r *RegisteredWebhookWithStatusBackup) GetURL() *string {
	if r == nil {
		return nil
	}
	return r.URL
}

// RegisteredWebhookWithStatusCallbackURL - Callback URLs where events will be sent
type RegisteredWebhookWithStatusCallbackURL struct {
	// Primary URL where events will be sent
	Main *RegisteredWebhookWithStatusMain `json:"main,omitzero"`
	// Secondary URL where events will be sent whenever the primary URL is not responding
	Backup *RegisteredWebhookWithStatusBackup `json:"backup,omitzero"`
}

func (r RegisteredWebhookWithStatusCallbackURL) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RegisteredWebhookWithStatusCallbackURL) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RegisteredWebhookWithStatusCallbackURL) GetMain() *RegisteredWebhookWithStatusMain {
	if r == nil {
		return nil
	}
	return r.Main
}

func (r *RegisteredWebhookWithStatusCallbackURL) GetBackup() *RegisteredWebhookWithStatusBackup {
	if r == nil {
		return nil
	}
	return r.Backup
}

type RegisteredWebhookWithStatus struct {
	// This webhook's ID, used to update or remove the webhook
	ID            *string  `json:"id,omitzero"`
	ApplicationID *string  `json:"applicationId,omitzero"`
	Categories    []string `json:"categories,omitzero"`
	// Callback URLs where events will be sent
	CallbackURL *RegisteredWebhookWithStatusCallbackURL `json:"callbackUrl,omitzero"`
	// Any data (under 10kB total) that should be associated with the Webhook. A copy of this data will be returned on every Webhook trigger.
	Metadata map[string]string  `json:"metadata,omitzero"`
	Status   *WebhookStatusType `json:"status,omitzero"`
}

func (r RegisteredWebhookWithStatus) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RegisteredWebhookWithStatus) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RegisteredWebhookWithStatus) GetID() *string {
	if r == nil {
		return nil
	}
	return r.ID
}

func (r *RegisteredWebhookWithStatus) GetApplicationID() *string {
	if r == nil {
		return nil
	}
	return r.ApplicationID
}

func (r *RegisteredWebhookWithStatus) GetCategories() []string {
	if r == nil {
		return nil
	}
	return r.Categories
}

func (r *RegisteredWebhookWithStatus) GetCallbackURL() *RegisteredWebhookWithStatusCallbackURL {
	if r == nil {
		return nil
	}
	return r.CallbackURL
}

func (r *RegisteredWebhookWithStatus) GetMetadata() map[string]string {
	if r == nil {
		return nil
	}
	return r.Metadata
}

func (r *RegisteredWebhookWithStatus) GetStatus() *WebhookStatusType {
	if r == nil {
		return nil
	}
	return r.Status
}
