// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// RequestConstraints - Object defining the constraints rules applicable for a given requests.
type RequestConstraints struct {
	Headers *Schema `json:"headers,omitzero"`
	Body    Schema  `json:"body"`
}

func (r RequestConstraints) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RequestConstraints) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RequestConstraints) GetHeaders() *Schema {
	if r == nil {
		return nil
	}
	return r.Headers
}

func (r *RequestConstraints) GetBody() Schema {
	if r == nil {
		return Schema{}
	}
	return r.Body
}
