// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ResponseMeta struct {
	TracingID *string `json:"tracingId,omitzero"`
}

func (r *ResponseMeta) GetTracingID() *string {
	if r == nil {
		return nil
	}
	return r.TracingID
}
