// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type ResponseListMeta struct {
	TracingID  *string     `json:"tracingId,omitzero"`
	Count      *int        `json:"count,omitzero"`
	Pagination *Pagination `json:"pagination,omitzero"`
}

func (r ResponseListMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResponseListMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ResponseListMeta) GetTracingID() *string {
	if r == nil {
		return nil
	}
	return r.TracingID
}

func (r *ResponseListMeta) GetCount() *int {
	if r == nil {
		return nil
	}
	return r.Count
}

func (r *ResponseListMeta) GetPagination() *Pagination {
	if r == nil {
		return nil
	}
	return r.Pagination
}
