// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type SearchApplicationsParameters struct {
	// Sub-application ids to filter the results for. If provided, the results will only include sub-applications with the given ids. Non-existent ids will be ignored.
	ApplicationIds []string `queryParam:"name=applicationIds"`
	// The number of results to skip.
	Offset *int64 `default:"0" queryParam:"name=offset"`
	// The maximum number of results to return.
	Limit *int64 `default:"1000" queryParam:"name=limit"`
	// The field to sort the results by.
	//
	// Possible values:
	//
	// - `last_updated` (ascending)
	// - `-last_updated` (descending)
	// - `name` (ascending)
	// - `-name` (descending)
	// - `uuid` (ascending)
	// - `-uuid` (descending)
	Sort *string `default:"name" queryParam:"name=sort"`
}

func (s SearchApplicationsParameters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchApplicationsParameters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchApplicationsParameters) GetApplicationIds() []string {
	if s == nil {
		return nil
	}
	return s.ApplicationIds
}

func (s *SearchApplicationsParameters) GetOffset() *int64 {
	if s == nil {
		return nil
	}
	return s.Offset
}

func (s *SearchApplicationsParameters) GetLimit() *int64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

func (s *SearchApplicationsParameters) GetSort() *string {
	if s == nil {
		return nil
	}
	return s.Sort
}
