// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// StatementReference - Unique reference for a statement period. This may be optionally populated if available.
type StatementReference struct {
	Value *string `json:"value,omitzero"`
}

func (s *StatementReference) GetValue() *string {
	if s == nil {
		return nil
	}
	return s.Value
}
