// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// TransactionHash - An unique identifier for the transaction that was generated by Yapily. This is a hash of transaction attributes and may be useful an id is not present (and therefore hasn't been provided by an Institution).
type TransactionHash struct {
	Hash *string `json:"hash,omitzero"`
}

func (t *TransactionHash) GetHash() *string {
	if t == nil {
		return nil
	}
	return t.Hash
}
