// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// Type - The `SCA` method type available for the user
type Type string

const (
	TypeSmsOtp   Type = "SMS_OTP"
	TypeChipOtp  Type = "CHIP_OTP"
	TypePhotoOtp Type = "PHOTO_OTP"
	TypePushOtp  Type = "PUSH_OTP"
)

func (e Type) ToPointer() *Type {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Type) IsExact() bool {
	if e != nil {
		switch *e {
		case "SMS_OTP", "CHIP_OTP", "PHOTO_OTP", "PUSH_OTP":
			return true
		}
	}
	return false
}
