// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UsageType - The customer segment of the account.
type UsageType string

const (
	UsageTypePersonal UsageType = "PERSONAL"
	UsageTypeBusiness UsageType = "BUSINESS"
	UsageTypeOther    UsageType = "OTHER"
	UsageTypeUnknown  UsageType = "UNKNOWN"
)

func (e UsageType) ToPointer() *UsageType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UsageType) IsExact() bool {
	if e != nil {
		switch *e {
		case "PERSONAL", "BUSINESS", "OTHER", "UNKNOWN":
			return true
		}
	}
	return false
}
