// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// UserBeneficiaryMatch - Details of the match given by the institution.
type UserBeneficiaryMatch struct {
	Status *BeneficiaryMatchStatus `json:"status,omitzero"`
	// the name returned by the institution, in a case of CLOSE_MATCH
	CloseMatchName *string `json:"closeMatchName,omitzero"`
}

func (u *UserBeneficiaryMatch) GetStatus() *BeneficiaryMatchStatus {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UserBeneficiaryMatch) GetCloseMatchName() *string {
	if u == nil {
		return nil
	}
	return u.CloseMatchName
}
