// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ValidationError struct {
	// name of the field with error
	FieldName string    `json:"fieldName"`
	Error     EnumError `json:"error"`
}

func (v *ValidationError) GetFieldName() string {
	if v == nil {
		return ""
	}
	return v.FieldName
}

func (v *ValidationError) GetError() EnumError {
	if v == nil {
		return EnumError("")
	}
	return v.Error
}
