// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/types"
)

// VrpComplianceDataIndividual - __Conditional__. Mandatory if the type is INDIVIDUAL.
type VrpComplianceDataIndividual struct {
	// This is the first and last name of your end user.
	Name string `json:"name"`
	// This is the date of birth of your end user.
	BirthDate types.Date `json:"birthDate"`
}

func (v VrpComplianceDataIndividual) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VrpComplianceDataIndividual) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VrpComplianceDataIndividual) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *VrpComplianceDataIndividual) GetBirthDate() types.Date {
	if v == nil {
		return types.Date{}
	}
	return v.BirthDate
}
