// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// VrpComplianceDataPayer - __Conditional__. Payer details required for compliance checks.
type VrpComplianceDataPayer struct {
	// The payer type. Allowed values: INDIVIDUAL, BUSINESS. The corresponding object must be included.
	Type string `json:"type"`
	// __Conditional__. Mandatory if the type is INDIVIDUAL.
	Individual *VrpComplianceDataIndividual `json:"individual,omitzero"`
	// __Conditional__. Mandatory if the type is BUSINESS.
	Business *VrpComplianceDataBusiness `json:"business,omitzero"`
}

func (v VrpComplianceDataPayer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VrpComplianceDataPayer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VrpComplianceDataPayer) GetType() string {
	if v == nil {
		return ""
	}
	return v.Type
}

func (v *VrpComplianceDataPayer) GetIndividual() *VrpComplianceDataIndividual {
	if v == nil {
		return nil
	}
	return v.Individual
}

func (v *VrpComplianceDataPayer) GetBusiness() *VrpComplianceDataBusiness {
	if v == nil {
		return nil
	}
	return v.Business
}
