// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// VrpComplianceDataBusiness - __Conditional__. Mandatory if the type is BUSINESS.
type VrpComplianceDataBusiness struct {
	// This is the registered company name of your end user.
	Name string `json:"name"`
	// This is the registered company number of the business.
	RegistrationNumber string `json:"registrationNumber"`
	// This is the registered company or trading address of your end user.
	RegisteredAddress VrpComplianceDataAddress `json:"registeredAddress"`
	// This is the registered company or trading address of your end user.
	TradingAddress *VrpComplianceDataAddress `json:"tradingAddress,omitzero"`
}

func (v VrpComplianceDataBusiness) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VrpComplianceDataBusiness) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VrpComplianceDataBusiness) GetName() string {
	if v == nil {
		return ""
	}
	return v.Name
}

func (v *VrpComplianceDataBusiness) GetRegistrationNumber() string {
	if v == nil {
		return ""
	}
	return v.RegistrationNumber
}

func (v *VrpComplianceDataBusiness) GetRegisteredAddress() VrpComplianceDataAddress {
	if v == nil {
		return VrpComplianceDataAddress{}
	}
	return v.RegisteredAddress
}

func (v *VrpComplianceDataBusiness) GetTradingAddress() *VrpComplianceDataAddress {
	if v == nil {
		return nil
	}
	return v.TradingAddress
}
