// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VrpCommercialRiskDetails - The details required by the institutions to detect and prevent fraud.
type VrpCommercialRiskDetails struct {
	PaymentContextCode  string `json:"paymentContextCode"`
	PaymentPurposeCode  string `json:"paymentPurposeCode"`
	CategoryPurposeCode string `json:"categoryPurposeCode"`
	// The merchant's identifier for the customer associated with the payment.
	MerchantCustomerID string `json:"merchantCustomerId"`
	// Set to `true` when you have a contractual relationship with Yapily. This is overridden according to the value in your application configuration.
	IsContractPresent bool `json:"isContractPresent"`
	// Set to `true` when the `payee` details were populated automatically (as opposed to being manually provided by the payee).
	IsPayeePrepopulated bool    `json:"isPayeePrepopulated"`
	PayeeAccountType    *string `json:"payeeAccountType,omitzero"`
}

func (v *VrpCommercialRiskDetails) GetPaymentContextCode() string {
	if v == nil {
		return ""
	}
	return v.PaymentContextCode
}

func (v *VrpCommercialRiskDetails) GetPaymentPurposeCode() string {
	if v == nil {
		return ""
	}
	return v.PaymentPurposeCode
}

func (v *VrpCommercialRiskDetails) GetCategoryPurposeCode() string {
	if v == nil {
		return ""
	}
	return v.CategoryPurposeCode
}

func (v *VrpCommercialRiskDetails) GetMerchantCustomerID() string {
	if v == nil {
		return ""
	}
	return v.MerchantCustomerID
}

func (v *VrpCommercialRiskDetails) GetIsContractPresent() bool {
	if v == nil {
		return false
	}
	return v.IsContractPresent
}

func (v *VrpCommercialRiskDetails) GetIsPayeePrepopulated() bool {
	if v == nil {
		return false
	}
	return v.IsPayeePrepopulated
}

func (v *VrpCommercialRiskDetails) GetPayeeAccountType() *string {
	if v == nil {
		return nil
	}
	return v.PayeeAccountType
}
