// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VrpFundsConfirmationRequest struct {
	// __Mandatory__. Monetary Amount.
	PaymentAmount Amount `json:"paymentAmount"`
	// __Optional__. The reference/description associated with the VRP consent. Limited to a maximum of 18 characters long.
	Reference *string `json:"reference,omitzero"`
}

func (v *VrpFundsConfirmationRequest) GetPaymentAmount() Amount {
	if v == nil {
		return Amount{}
	}
	return v.PaymentAmount
}

func (v *VrpFundsConfirmationRequest) GetReference() *string {
	if v == nil {
		return nil
	}
	return v.Reference
}
