// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

// VrpInitiationDetails - The definition of the payer and payee.
type VrpInitiationDetails struct {
	// The reference/description of the payments that will be carried out on this VRP consent.
	Reference *string `json:"reference,omitzero"`
	// __Conditional__. Details of the benefactor [person or business].
	Payer         *Payer            `json:"payer,omitzero"`
	UltimatePayer *VrpUltimatePayer `json:"ultimatePayer,omitzero"`
	// __Mandatory__. Details of the beneficiary [person or business].
	Payee         *Payee            `json:"payee,omitzero"`
	UltimatePayee *VrpUltimatePayee `json:"ultimatePayee,omitzero"`
}

func (v VrpInitiationDetails) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VrpInitiationDetails) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VrpInitiationDetails) GetReference() *string {
	if v == nil {
		return nil
	}
	return v.Reference
}

func (v *VrpInitiationDetails) GetPayer() *Payer {
	if v == nil {
		return nil
	}
	return v.Payer
}

func (v *VrpInitiationDetails) GetUltimatePayer() *VrpUltimatePayer {
	if v == nil {
		return nil
	}
	return v.UltimatePayer
}

func (v *VrpInitiationDetails) GetPayee() *Payee {
	if v == nil {
		return nil
	}
	return v.Payee
}

func (v *VrpInitiationDetails) GetUltimatePayee() *VrpUltimatePayee {
	if v == nil {
		return nil
	}
	return v.UltimatePayee
}
