// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type VrpPeriodicLimits struct {
	// __Mandatory__. The frequency/period over which the limit is enforced.
	// Allowed values are [`DAILY`, `WEEKLY`, `EVERY_TWO_WEEKS`, `MONTHLY`, `YEARLY`].
	Frequency string `json:"frequency"`
	// __Mandatory__. The maximum amount that will be allowed over the specified frequency/period.
	//
	// If the `alignment` is set to `CALENDAR`, then the limit will be [pro-rated](/payments/vrps/mandate-details#pro-rata-calculation) in the first period to the remaining number of days.
	TotalMaxAmount Amount `json:"totalMaxAmount"`
	// __Mandatory__. The alignment of the frequency/period for which the limit is enforced. Allowed values are [`CONSENT`, `CALENDAR`].
	//
	// See [VRP Mandate Details](/payments/vrps/mandate-details).
	Alignment string `json:"alignment"`
}

func (v *VrpPeriodicLimits) GetFrequency() string {
	if v == nil {
		return ""
	}
	return v.Frequency
}

func (v *VrpPeriodicLimits) GetTotalMaxAmount() Amount {
	if v == nil {
		return Amount{}
	}
	return v.TotalMaxAmount
}

func (v *VrpPeriodicLimits) GetAlignment() string {
	if v == nil {
		return ""
	}
	return v.Alignment
}
