// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VrpSubmissionRequest - __Mandatory__. The payment request object defining the details of the payment for execution under the Variable Recurring Payment consent.
type VrpSubmissionRequest struct {
	// __Mandatory__. A unique identifier for the payment.
	//
	// This can be any alpha-numeric string but is limited to a maximum of 35 characters.
	PaymentIdempotencyID string `json:"paymentIdempotencyId"`
	// __Mandatory__. Defines the authentication method(s) allowed in payment submission step.
	// Allowed values are [`SCA_REQUIRED`, `SCA_NOT_REQUIRED`].
	//
	// See [SCA](/getting-started/glossary#strong-customer-authentication-sca).
	PsuAuthenticationMethod string `json:"psuAuthenticationMethod"`
	// __Conditional__. This value is mandatory for Commercial VRP payments. It is one of `PSU_PRESENT` (ie. the PSU oversees the payment) or `PSU_NOT_PRESENT` (eg. the payment is async).
	PsuInteractionType *string `json:"psuInteractionType,omitzero"`
	// __Mandatory__. Monetary Amount.
	PaymentAmount Amount `json:"paymentAmount"`
}

func (v *VrpSubmissionRequest) GetPaymentIdempotencyID() string {
	if v == nil {
		return ""
	}
	return v.PaymentIdempotencyID
}

func (v *VrpSubmissionRequest) GetPsuAuthenticationMethod() string {
	if v == nil {
		return ""
	}
	return v.PsuAuthenticationMethod
}

func (v *VrpSubmissionRequest) GetPsuInteractionType() *string {
	if v == nil {
		return nil
	}
	return v.PsuInteractionType
}

func (v *VrpSubmissionRequest) GetPaymentAmount() Amount {
	if v == nil {
		return Amount{}
	}
	return v.PaymentAmount
}
