// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// VrpSweepingRiskDetails - The details required by the institutions to detect and prevent fraud.
type VrpSweepingRiskDetails struct {
	PaymentContextCode *string `json:"paymentContextCode,omitzero"`
}

func (v *VrpSweepingRiskDetails) GetPaymentContextCode() *string {
	if v == nil {
		return nil
	}
	return v.PaymentContextCode
}
