// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
	"time"
)

type VrpSubmissionResponse struct {
	// The Payment ID.
	ID *string `json:"id,omitzero"`
	// The Payment Idempotency ID (as provided in the request).
	PaymentIdempotencyID *string `json:"paymentIdempotencyId,omitzero"`
	PaymentLifecycleID   *string `json:"paymentLifecycleId,omitzero"`
	// The Institution's Consent ID on which the payment was submitted. Note that this cannot be used to interact with Yapily API.
	InstitutionConsentID *string `json:"institutionConsentId,omitzero"`
	// The status of the Payment.
	//
	// For more information, see [Payment Status](/guides/payments/payment-status/)
	Status        *PaymentStatus        `json:"status,omitzero"`
	StatusDetails *PaymentStatusDetails `json:"statusDetails,omitzero"`
	// The definition of the payer and payee.
	InitiationDetails VrpInitiationDetails `json:"initiationDetails"`
	// __Mandatory__. The payment submission object defining the details of the payment instruction to be executed under the Variable Recurring Payment.
	SubmissionDetails VrpSubmissionDetails `json:"submissionDetails"`
	// __Conditional__. Details of the benefactor [person or business].
	Payer *Payer `json:"payer,omitzero"`
	// The account to which funds should be returned if the payment is to be later refunded.
	RefundAccount          *RefundAccount `json:"refundAccount,omitzero"`
	ExpectedExecutionTime  *time.Time     `json:"expectedExecutionTime,omitzero"`
	ExpectedSettlementTime *time.Time     `json:"expectedSettlementTime,omitzero"`
	// The details required by the institutions to detect and prevent fraud.
	RiskDetails *VrpSweepingRiskDetails `json:"riskDetails,omitzero"`
}

func (v VrpSubmissionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VrpSubmissionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VrpSubmissionResponse) GetID() *string {
	if v == nil {
		return nil
	}
	return v.ID
}

func (v *VrpSubmissionResponse) GetPaymentIdempotencyID() *string {
	if v == nil {
		return nil
	}
	return v.PaymentIdempotencyID
}

func (v *VrpSubmissionResponse) GetPaymentLifecycleID() *string {
	if v == nil {
		return nil
	}
	return v.PaymentLifecycleID
}

func (v *VrpSubmissionResponse) GetInstitutionConsentID() *string {
	if v == nil {
		return nil
	}
	return v.InstitutionConsentID
}

func (v *VrpSubmissionResponse) GetStatus() *PaymentStatus {
	if v == nil {
		return nil
	}
	return v.Status
}

func (v *VrpSubmissionResponse) GetStatusDetails() *PaymentStatusDetails {
	if v == nil {
		return nil
	}
	return v.StatusDetails
}

func (v *VrpSubmissionResponse) GetInitiationDetails() VrpInitiationDetails {
	if v == nil {
		return VrpInitiationDetails{}
	}
	return v.InitiationDetails
}

func (v *VrpSubmissionResponse) GetSubmissionDetails() VrpSubmissionDetails {
	if v == nil {
		return VrpSubmissionDetails{}
	}
	return v.SubmissionDetails
}

func (v *VrpSubmissionResponse) GetPayer() *Payer {
	if v == nil {
		return nil
	}
	return v.Payer
}

func (v *VrpSubmissionResponse) GetRefundAccount() *RefundAccount {
	if v == nil {
		return nil
	}
	return v.RefundAccount
}

func (v *VrpSubmissionResponse) GetExpectedExecutionTime() *time.Time {
	if v == nil {
		return nil
	}
	return v.ExpectedExecutionTime
}

func (v *VrpSubmissionResponse) GetExpectedSettlementTime() *time.Time {
	if v == nil {
		return nil
	}
	return v.ExpectedSettlementTime
}

func (v *VrpSubmissionResponse) GetRiskDetails() *VrpSweepingRiskDetails {
	if v == nil {
		return nil
	}
	return v.RiskDetails
}
