// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/MinhalAhmedKhan/yapily-go-sdk/internal/utils"
)

type VrpUltimatePayee struct {
	Name                      *string                 `json:"name,omitzero"`
	AccountIdentifications    []AccountIdentification `json:"accountIdentifications,omitzero"`
	LegalEntityIdentification *string                 `json:"legalEntityIdentification,omitzero"`
	// __Optional__. The payee account type.
	//
	// Allowed values: BUSINESS, BUSINESS_SAVING, CHARITY, COLLECTION, CORPORATE, E_WALLET, GOVERNMENT, INVESTMENT, INVESTMENT_ISA, JOINT_PERSONAL, PENSION, PERSONAL, PERSONAL_SAVING, PREMIER, WEALTH .
	AccountType *string `json:"accountType,omitzero"`
	// __Conditional__. The address of the `Payee` or `Payer`.
	//
	// - `payee.address` is mandatory when the `paymentType` is an `INTERNATIONAL` payment
	// - An `Institution` may require you to specify the `country` when used in the context of the `Payee` to be able to make a payment.
	Address              *Address `json:"address,omitzero"`
	MerchantID           *string  `json:"merchantId,omitzero"`
	MerchantCategoryCode *string  `json:"merchantCategoryCode,omitzero"`
}

func (v VrpUltimatePayee) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VrpUltimatePayee) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VrpUltimatePayee) GetName() *string {
	if v == nil {
		return nil
	}
	return v.Name
}

func (v *VrpUltimatePayee) GetAccountIdentifications() []AccountIdentification {
	if v == nil {
		return nil
	}
	return v.AccountIdentifications
}

func (v *VrpUltimatePayee) GetLegalEntityIdentification() *string {
	if v == nil {
		return nil
	}
	return v.LegalEntityIdentification
}

func (v *VrpUltimatePayee) GetAccountType() *string {
	if v == nil {
		return nil
	}
	return v.AccountType
}

func (v *VrpUltimatePayee) GetAddress() *Address {
	if v == nil {
		return nil
	}
	return v.Address
}

func (v *VrpUltimatePayee) GetMerchantID() *string {
	if v == nil {
		return nil
	}
	return v.MerchantID
}

func (v *VrpUltimatePayee) GetMerchantCategoryCode() *string {
	if v == nil {
		return nil
	}
	return v.MerchantCategoryCode
}
