// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WebhookStatusType string

const (
	WebhookStatusTypeActive WebhookStatusType = "active"
	WebhookStatusTypePaused WebhookStatusType = "paused"
)

func (e WebhookStatusType) ToPointer() *WebhookStatusType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WebhookStatusType) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "paused":
			return true
		}
	}
	return false
}
