// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/MinhalAhmedKhan/yapily-go-sdk/models/components"
)

type ValidationErrorResponse struct {
	Errors   []components.ValidationError `json:"errors,omitzero"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &ValidationErrorResponse{}

func (e *ValidationErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
