workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Yapily API:
        inputs:
            - location: ../../Downloads/openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/test-slz/my-workspace/yapily-api
targets:
    yapily:
        target: go
        source: Yapily API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/test-slz/my-workspace/yapily-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
